/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for AbbreviatedPaymentPerformanceDetails type.
 */
public class AbbreviatedPaymentPerformanceDetails {
    private String allDataInRange;
    private Integer numberCashFirst;
    private Integer numberCollection;
    private Double valCollection;
    private Integer numberCollectionLast2Years;
    private Integer acctsUnpaid1Month;
    private Integer acctsUnpaid2Months;
    private Integer acctsUnpaid3Months;
    private Integer numMnths;
    private List<DebitMonthly> dBTMonthly;

    /**
     * Default constructor.
     */
    public AbbreviatedPaymentPerformanceDetails() {
    }

    /**
     * Initialization constructor.
     * @param  allDataInRange  String value for allDataInRange.
     * @param  numberCashFirst  Integer value for numberCashFirst.
     * @param  numberCollection  Integer value for numberCollection.
     * @param  valCollection  Double value for valCollection.
     * @param  numberCollectionLast2Years  Integer value for numberCollectionLast2Years.
     * @param  acctsUnpaid1Month  Integer value for acctsUnpaid1Month.
     * @param  acctsUnpaid2Months  Integer value for acctsUnpaid2Months.
     * @param  acctsUnpaid3Months  Integer value for acctsUnpaid3Months.
     * @param  numMnths  Integer value for numMnths.
     * @param  dBTMonthly  List of DebitMonthly value for dBTMonthly.
     */
    public AbbreviatedPaymentPerformanceDetails(
            String allDataInRange,
            Integer numberCashFirst,
            Integer numberCollection,
            Double valCollection,
            Integer numberCollectionLast2Years,
            Integer acctsUnpaid1Month,
            Integer acctsUnpaid2Months,
            Integer acctsUnpaid3Months,
            Integer numMnths,
            List<DebitMonthly> dBTMonthly) {
        this.allDataInRange = allDataInRange;
        this.numberCashFirst = numberCashFirst;
        this.numberCollection = numberCollection;
        this.valCollection = valCollection;
        this.numberCollectionLast2Years = numberCollectionLast2Years;
        this.acctsUnpaid1Month = acctsUnpaid1Month;
        this.acctsUnpaid2Months = acctsUnpaid2Months;
        this.acctsUnpaid3Months = acctsUnpaid3Months;
        this.numMnths = numMnths;
        this.dBTMonthly = dBTMonthly;
    }

    /**
     * Getter for AllDataInRange.
     * Indicator showing whether all the Abbreviated Payment data is in the ownership period - G =
     * Yes, L = No
     * @return Returns the String
     */
    @JsonGetter("AllDataInRange")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAllDataInRange() {
        return allDataInRange;
    }

    /**
     * Setter for AllDataInRange.
     * Indicator showing whether all the Abbreviated Payment data is in the ownership period - G =
     * Yes, L = No
     * @param allDataInRange Value for String
     */
    @JsonSetter("AllDataInRange")
    public void setAllDataInRange(String allDataInRange) {
        this.allDataInRange = allDataInRange;
    }

    /**
     * Getter for NumberCashFirst.
     * Number of accounts that are Cash First or Pro forma
     * @return Returns the Integer
     */
    @JsonGetter("NumberCashFirst")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumberCashFirst() {
        return numberCashFirst;
    }

    /**
     * Setter for NumberCashFirst.
     * Number of accounts that are Cash First or Pro forma
     * @param numberCashFirst Value for Integer
     */
    @JsonSetter("NumberCashFirst")
    public void setNumberCashFirst(Integer numberCashFirst) {
        this.numberCashFirst = numberCashFirst;
    }

    /**
     * Getter for NumberCollection.
     * Number of accounts that are placed for Collection
     * @return Returns the Integer
     */
    @JsonGetter("NumberCollection")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumberCollection() {
        return numberCollection;
    }

    /**
     * Setter for NumberCollection.
     * Number of accounts that are placed for Collection
     * @param numberCollection Value for Integer
     */
    @JsonSetter("NumberCollection")
    public void setNumberCollection(Integer numberCollection) {
        this.numberCollection = numberCollection;
    }

    /**
     * Getter for ValCollection.
     * Value of accounts that are placed for Collection
     * @return Returns the Double
     */
    @JsonGetter("ValCollection")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getValCollection() {
        return valCollection;
    }

    /**
     * Setter for ValCollection.
     * Value of accounts that are placed for Collection
     * @param valCollection Value for Double
     */
    @JsonSetter("ValCollection")
    public void setValCollection(Double valCollection) {
        this.valCollection = valCollection;
    }

    /**
     * Getter for NumberCollectionLast2Years.
     * Number of accounts that have been placed for Collection in the last 2 years
     * @return Returns the Integer
     */
    @JsonGetter("NumberCollectionLast2Years")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumberCollectionLast2Years() {
        return numberCollectionLast2Years;
    }

    /**
     * Setter for NumberCollectionLast2Years.
     * Number of accounts that have been placed for Collection in the last 2 years
     * @param numberCollectionLast2Years Value for Integer
     */
    @JsonSetter("NumberCollectionLast2Years")
    public void setNumberCollectionLast2Years(Integer numberCollectionLast2Years) {
        this.numberCollectionLast2Years = numberCollectionLast2Years;
    }

    /**
     * Getter for AcctsUnpaid1Month.
     * Number of accounts that have been unpaid for the last month
     * @return Returns the Integer
     */
    @JsonGetter("AcctsUnpaid1Month")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAcctsUnpaid1Month() {
        return acctsUnpaid1Month;
    }

    /**
     * Setter for AcctsUnpaid1Month.
     * Number of accounts that have been unpaid for the last month
     * @param acctsUnpaid1Month Value for Integer
     */
    @JsonSetter("AcctsUnpaid1Month")
    public void setAcctsUnpaid1Month(Integer acctsUnpaid1Month) {
        this.acctsUnpaid1Month = acctsUnpaid1Month;
    }

    /**
     * Getter for AcctsUnpaid2Months.
     * Number of accounts that have been unpaid for the last 3 months
     * @return Returns the Integer
     */
    @JsonGetter("AcctsUnpaid2Months")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAcctsUnpaid2Months() {
        return acctsUnpaid2Months;
    }

    /**
     * Setter for AcctsUnpaid2Months.
     * Number of accounts that have been unpaid for the last 3 months
     * @param acctsUnpaid2Months Value for Integer
     */
    @JsonSetter("AcctsUnpaid2Months")
    public void setAcctsUnpaid2Months(Integer acctsUnpaid2Months) {
        this.acctsUnpaid2Months = acctsUnpaid2Months;
    }

    /**
     * Getter for AcctsUnpaid3Months.
     * Number of accounts that have been unpaid for the last 2 months
     * @return Returns the Integer
     */
    @JsonGetter("AcctsUnpaid3Months")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAcctsUnpaid3Months() {
        return acctsUnpaid3Months;
    }

    /**
     * Setter for AcctsUnpaid3Months.
     * Number of accounts that have been unpaid for the last 2 months
     * @param acctsUnpaid3Months Value for Integer
     */
    @JsonSetter("AcctsUnpaid3Months")
    public void setAcctsUnpaid3Months(Integer acctsUnpaid3Months) {
        this.acctsUnpaid3Months = acctsUnpaid3Months;
    }

    /**
     * Getter for NumMnths.
     * @return Returns the Integer
     */
    @JsonGetter("NumMnths")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumMnths() {
        return numMnths;
    }

    /**
     * Setter for NumMnths.
     * @param numMnths Value for Integer
     */
    @JsonSetter("NumMnths")
    public void setNumMnths(Integer numMnths) {
        this.numMnths = numMnths;
    }

    /**
     * Getter for DBTMonthly.
     * @return Returns the List of DebitMonthly
     */
    @JsonGetter("DBTMonthly")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DebitMonthly> getDBTMonthly() {
        return dBTMonthly;
    }

    /**
     * Setter for DBTMonthly.
     * @param dBTMonthly Value for List of DebitMonthly
     */
    @JsonSetter("DBTMonthly")
    public void setDBTMonthly(List<DebitMonthly> dBTMonthly) {
        this.dBTMonthly = dBTMonthly;
    }

    /**
     * Converts this AbbreviatedPaymentPerformanceDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AbbreviatedPaymentPerformanceDetails [" + "allDataInRange=" + allDataInRange
                + ", numberCashFirst=" + numberCashFirst + ", numberCollection=" + numberCollection
                + ", valCollection=" + valCollection + ", numberCollectionLast2Years="
                + numberCollectionLast2Years + ", acctsUnpaid1Month=" + acctsUnpaid1Month
                + ", acctsUnpaid2Months=" + acctsUnpaid2Months + ", acctsUnpaid3Months="
                + acctsUnpaid3Months + ", numMnths=" + numMnths + ", dBTMonthly=" + dBTMonthly
                + "]";
    }

    /**
     * Builds a new {@link AbbreviatedPaymentPerformanceDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AbbreviatedPaymentPerformanceDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .allDataInRange(getAllDataInRange())
                .numberCashFirst(getNumberCashFirst())
                .numberCollection(getNumberCollection())
                .valCollection(getValCollection())
                .numberCollectionLast2Years(getNumberCollectionLast2Years())
                .acctsUnpaid1Month(getAcctsUnpaid1Month())
                .acctsUnpaid2Months(getAcctsUnpaid2Months())
                .acctsUnpaid3Months(getAcctsUnpaid3Months())
                .numMnths(getNumMnths())
                .dBTMonthly(getDBTMonthly());
        return builder;
    }

    /**
     * Class to build instances of {@link AbbreviatedPaymentPerformanceDetails}.
     */
    public static class Builder {
        private String allDataInRange;
        private Integer numberCashFirst;
        private Integer numberCollection;
        private Double valCollection;
        private Integer numberCollectionLast2Years;
        private Integer acctsUnpaid1Month;
        private Integer acctsUnpaid2Months;
        private Integer acctsUnpaid3Months;
        private Integer numMnths;
        private List<DebitMonthly> dBTMonthly;



        /**
         * Setter for allDataInRange.
         * @param  allDataInRange  String value for allDataInRange.
         * @return Builder
         */
        public Builder allDataInRange(String allDataInRange) {
            this.allDataInRange = allDataInRange;
            return this;
        }

        /**
         * Setter for numberCashFirst.
         * @param  numberCashFirst  Integer value for numberCashFirst.
         * @return Builder
         */
        public Builder numberCashFirst(Integer numberCashFirst) {
            this.numberCashFirst = numberCashFirst;
            return this;
        }

        /**
         * Setter for numberCollection.
         * @param  numberCollection  Integer value for numberCollection.
         * @return Builder
         */
        public Builder numberCollection(Integer numberCollection) {
            this.numberCollection = numberCollection;
            return this;
        }

        /**
         * Setter for valCollection.
         * @param  valCollection  Double value for valCollection.
         * @return Builder
         */
        public Builder valCollection(Double valCollection) {
            this.valCollection = valCollection;
            return this;
        }

        /**
         * Setter for numberCollectionLast2Years.
         * @param  numberCollectionLast2Years  Integer value for numberCollectionLast2Years.
         * @return Builder
         */
        public Builder numberCollectionLast2Years(Integer numberCollectionLast2Years) {
            this.numberCollectionLast2Years = numberCollectionLast2Years;
            return this;
        }

        /**
         * Setter for acctsUnpaid1Month.
         * @param  acctsUnpaid1Month  Integer value for acctsUnpaid1Month.
         * @return Builder
         */
        public Builder acctsUnpaid1Month(Integer acctsUnpaid1Month) {
            this.acctsUnpaid1Month = acctsUnpaid1Month;
            return this;
        }

        /**
         * Setter for acctsUnpaid2Months.
         * @param  acctsUnpaid2Months  Integer value for acctsUnpaid2Months.
         * @return Builder
         */
        public Builder acctsUnpaid2Months(Integer acctsUnpaid2Months) {
            this.acctsUnpaid2Months = acctsUnpaid2Months;
            return this;
        }

        /**
         * Setter for acctsUnpaid3Months.
         * @param  acctsUnpaid3Months  Integer value for acctsUnpaid3Months.
         * @return Builder
         */
        public Builder acctsUnpaid3Months(Integer acctsUnpaid3Months) {
            this.acctsUnpaid3Months = acctsUnpaid3Months;
            return this;
        }

        /**
         * Setter for numMnths.
         * @param  numMnths  Integer value for numMnths.
         * @return Builder
         */
        public Builder numMnths(Integer numMnths) {
            this.numMnths = numMnths;
            return this;
        }

        /**
         * Setter for dBTMonthly.
         * @param  dBTMonthly  List of DebitMonthly value for dBTMonthly.
         * @return Builder
         */
        public Builder dBTMonthly(List<DebitMonthly> dBTMonthly) {
            this.dBTMonthly = dBTMonthly;
            return this;
        }

        /**
         * Builds a new {@link AbbreviatedPaymentPerformanceDetails} object using the set fields.
         * @return {@link AbbreviatedPaymentPerformanceDetails}
         */
        public AbbreviatedPaymentPerformanceDetails build() {
            return new AbbreviatedPaymentPerformanceDetails(allDataInRange, numberCashFirst,
                    numberCollection, valCollection, numberCollectionLast2Years, acctsUnpaid1Month,
                    acctsUnpaid2Months, acctsUnpaid3Months, numMnths, dBTMonthly);
        }
    }
}
