/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for ArrayOfStringLR type.
 */
public class ArrayOfStringLR {
    private List<String> errorCode;

    /**
     * Default constructor.
     */
    public ArrayOfStringLR() {
    }

    /**
     * Initialization constructor.
     * @param  errorCode  List of String value for errorCode.
     */
    public ArrayOfStringLR(
            List<String> errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * Getter for ErrorCode.
     * @return Returns the List of String
     */
    @JsonGetter("ErrorCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getErrorCode() {
        return errorCode;
    }

    /**
     * Setter for ErrorCode.
     * @param errorCode Value for List of String
     */
    @JsonSetter("ErrorCode")
    public void setErrorCode(List<String> errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * Converts this ArrayOfStringLR into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ArrayOfStringLR [" + "errorCode=" + errorCode + "]";
    }

    /**
     * Builds a new {@link ArrayOfStringLR.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ArrayOfStringLR.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .errorCode(getErrorCode());
        return builder;
    }

    /**
     * Class to build instances of {@link ArrayOfStringLR}.
     */
    public static class Builder {
        private List<String> errorCode;



        /**
         * Setter for errorCode.
         * @param  errorCode  List of String value for errorCode.
         * @return Builder
         */
        public Builder errorCode(List<String> errorCode) {
            this.errorCode = errorCode;
            return this;
        }

        /**
         * Builds a new {@link ArrayOfStringLR} object using the set fields.
         * @return {@link ArrayOfStringLR}
         */
        public ArrayOfStringLR build() {
            return new ArrayOfStringLR(errorCode);
        }
    }
}
