/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for ArrayOfString3 type.
 */
public class ArrayOfString3 {
    private List<String> ageHistoricalAverageDelphiScore;

    /**
     * Default constructor.
     */
    public ArrayOfString3() {
    }

    /**
     * Initialization constructor.
     * @param  ageHistoricalAverageDelphiScore  List of String value for
     *         ageHistoricalAverageDelphiScore.
     */
    public ArrayOfString3(
            List<String> ageHistoricalAverageDelphiScore) {
        this.ageHistoricalAverageDelphiScore = ageHistoricalAverageDelphiScore;
    }

    /**
     * Getter for AgeHistoricalAverageDelphiScore.
     * Historical Average Delphi Score - Age (x12) Occurs 12 times, monthly data for last year -
     * most recent first 0-100
     * @return Returns the List of String
     */
    @JsonGetter("AgeHistoricalAverageDelphiScore")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getAgeHistoricalAverageDelphiScore() {
        return ageHistoricalAverageDelphiScore;
    }

    /**
     * Setter for AgeHistoricalAverageDelphiScore.
     * Historical Average Delphi Score - Age (x12) Occurs 12 times, monthly data for last year -
     * most recent first 0-100
     * @param ageHistoricalAverageDelphiScore Value for List of String
     */
    @JsonSetter("AgeHistoricalAverageDelphiScore")
    public void setAgeHistoricalAverageDelphiScore(List<String> ageHistoricalAverageDelphiScore) {
        this.ageHistoricalAverageDelphiScore = ageHistoricalAverageDelphiScore;
    }

    /**
     * Converts this ArrayOfString3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ArrayOfString3 [" + "ageHistoricalAverageDelphiScore="
                + ageHistoricalAverageDelphiScore + "]";
    }

    /**
     * Builds a new {@link ArrayOfString3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ArrayOfString3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ageHistoricalAverageDelphiScore(getAgeHistoricalAverageDelphiScore());
        return builder;
    }

    /**
     * Class to build instances of {@link ArrayOfString3}.
     */
    public static class Builder {
        private List<String> ageHistoricalAverageDelphiScore;



        /**
         * Setter for ageHistoricalAverageDelphiScore.
         * @param  ageHistoricalAverageDelphiScore  List of String value for
         *         ageHistoricalAverageDelphiScore.
         * @return Builder
         */
        public Builder ageHistoricalAverageDelphiScore(
                List<String> ageHistoricalAverageDelphiScore) {
            this.ageHistoricalAverageDelphiScore = ageHistoricalAverageDelphiScore;
            return this;
        }

        /**
         * Builds a new {@link ArrayOfString3} object using the set fields.
         * @return {@link ArrayOfString3}
         */
        public ArrayOfString3 build() {
            return new ArrayOfString3(ageHistoricalAverageDelphiScore);
        }
    }
}
