/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for ArrayOfString2 type.
 */
public class ArrayOfString2 {
    private List<String> sizeHistoricalAverageDelphiScore;

    /**
     * Default constructor.
     */
    public ArrayOfString2() {
    }

    /**
     * Initialization constructor.
     * @param  sizeHistoricalAverageDelphiScore  List of String value for
     *         sizeHistoricalAverageDelphiScore.
     */
    public ArrayOfString2(
            List<String> sizeHistoricalAverageDelphiScore) {
        this.sizeHistoricalAverageDelphiScore = sizeHistoricalAverageDelphiScore;
    }

    /**
     * Getter for SizeHistoricalAverageDelphiScore.
     * Historical Average Delphi Score - Size (x12) Occurs 12 times, monthly data for last year -
     * most recent first 0-100
     * @return Returns the List of String
     */
    @JsonGetter("SizeHistoricalAverageDelphiScore")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getSizeHistoricalAverageDelphiScore() {
        return sizeHistoricalAverageDelphiScore;
    }

    /**
     * Setter for SizeHistoricalAverageDelphiScore.
     * Historical Average Delphi Score - Size (x12) Occurs 12 times, monthly data for last year -
     * most recent first 0-100
     * @param sizeHistoricalAverageDelphiScore Value for List of String
     */
    @JsonSetter("SizeHistoricalAverageDelphiScore")
    public void setSizeHistoricalAverageDelphiScore(List<String> sizeHistoricalAverageDelphiScore) {
        this.sizeHistoricalAverageDelphiScore = sizeHistoricalAverageDelphiScore;
    }

    /**
     * Converts this ArrayOfString2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ArrayOfString2 [" + "sizeHistoricalAverageDelphiScore="
                + sizeHistoricalAverageDelphiScore + "]";
    }

    /**
     * Builds a new {@link ArrayOfString2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ArrayOfString2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .sizeHistoricalAverageDelphiScore(getSizeHistoricalAverageDelphiScore());
        return builder;
    }

    /**
     * Class to build instances of {@link ArrayOfString2}.
     */
    public static class Builder {
        private List<String> sizeHistoricalAverageDelphiScore;



        /**
         * Setter for sizeHistoricalAverageDelphiScore.
         * @param  sizeHistoricalAverageDelphiScore  List of String value for
         *         sizeHistoricalAverageDelphiScore.
         * @return Builder
         */
        public Builder sizeHistoricalAverageDelphiScore(
                List<String> sizeHistoricalAverageDelphiScore) {
            this.sizeHistoricalAverageDelphiScore = sizeHistoricalAverageDelphiScore;
            return this;
        }

        /**
         * Builds a new {@link ArrayOfString2} object using the set fields.
         * @return {@link ArrayOfString2}
         */
        public ArrayOfString2 build() {
            return new ArrayOfString2(sizeHistoricalAverageDelphiScore);
        }
    }
}
