/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Bank type.
 */
public class Bank {
    private String bankSortcode;
    private String bankName;
    private LtdBusinessLocation bankLocation;

    /**
     * Default constructor.
     */
    public Bank() {
    }

    /**
     * Initialization constructor.
     * @param  bankSortcode  String value for bankSortcode.
     * @param  bankName  String value for bankName.
     * @param  bankLocation  LtdBusinessLocation value for bankLocation.
     */
    public Bank(
            String bankSortcode,
            String bankName,
            LtdBusinessLocation bankLocation) {
        this.bankSortcode = bankSortcode;
        this.bankName = bankName;
        this.bankLocation = bankLocation;
    }

    /**
     * Getter for BankSortcode.
     * Sort Code of the bank used by the limited company
     * @return Returns the String
     */
    @JsonGetter("BankSortcode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBankSortcode() {
        return bankSortcode;
    }

    /**
     * Setter for BankSortcode.
     * Sort Code of the bank used by the limited company
     * @param bankSortcode Value for String
     */
    @JsonSetter("BankSortcode")
    public void setBankSortcode(String bankSortcode) {
        this.bankSortcode = bankSortcode;
    }

    /**
     * Getter for BankName.
     * Bank name of the bank used by the limited company
     * @return Returns the String
     */
    @JsonGetter("BankName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBankName() {
        return bankName;
    }

    /**
     * Setter for BankName.
     * Bank name of the bank used by the limited company
     * @param bankName Value for String
     */
    @JsonSetter("BankName")
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * Getter for BankLocation.
     * @return Returns the LtdBusinessLocation
     */
    @JsonGetter("BankLocation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LtdBusinessLocation getBankLocation() {
        return bankLocation;
    }

    /**
     * Setter for BankLocation.
     * @param bankLocation Value for LtdBusinessLocation
     */
    @JsonSetter("BankLocation")
    public void setBankLocation(LtdBusinessLocation bankLocation) {
        this.bankLocation = bankLocation;
    }

    /**
     * Converts this Bank into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Bank [" + "bankSortcode=" + bankSortcode + ", bankName=" + bankName
                + ", bankLocation=" + bankLocation + "]";
    }

    /**
     * Builds a new {@link Bank.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Bank.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .bankSortcode(getBankSortcode())
                .bankName(getBankName())
                .bankLocation(getBankLocation());
        return builder;
    }

    /**
     * Class to build instances of {@link Bank}.
     */
    public static class Builder {
        private String bankSortcode;
        private String bankName;
        private LtdBusinessLocation bankLocation;



        /**
         * Setter for bankSortcode.
         * @param  bankSortcode  String value for bankSortcode.
         * @return Builder
         */
        public Builder bankSortcode(String bankSortcode) {
            this.bankSortcode = bankSortcode;
            return this;
        }

        /**
         * Setter for bankName.
         * @param  bankName  String value for bankName.
         * @return Builder
         */
        public Builder bankName(String bankName) {
            this.bankName = bankName;
            return this;
        }

        /**
         * Setter for bankLocation.
         * @param  bankLocation  LtdBusinessLocation value for bankLocation.
         * @return Builder
         */
        public Builder bankLocation(LtdBusinessLocation bankLocation) {
            this.bankLocation = bankLocation;
            return this;
        }

        /**
         * Builds a new {@link Bank} object using the set fields.
         * @return {@link Bank}
         */
        public Bank build() {
            return new Bank(bankSortcode, bankName, bankLocation);
        }
    }
}
