/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for BucketBlocks type.
 */
public class BucketBlocks {
    private List<String> bucketBlock;

    /**
     * Default constructor.
     */
    public BucketBlocks() {
    }

    /**
     * Initialization constructor.
     * @param  bucketBlock  List of String value for bucketBlock.
     */
    public BucketBlocks(
            List<String> bucketBlock) {
        this.bucketBlock = bucketBlock;
    }

    /**
     * Getter for BucketBlock.
     * @return Returns the List of String
     */
    @JsonGetter("BucketBlock")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getBucketBlock() {
        return bucketBlock;
    }

    /**
     * Setter for BucketBlock.
     * @param bucketBlock Value for List of String
     */
    @JsonSetter("BucketBlock")
    public void setBucketBlock(List<String> bucketBlock) {
        this.bucketBlock = bucketBlock;
    }

    /**
     * Converts this BucketBlocks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BucketBlocks [" + "bucketBlock=" + bucketBlock + "]";
    }

    /**
     * Builds a new {@link BucketBlocks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BucketBlocks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .bucketBlock(getBucketBlock());
        return builder;
    }

    /**
     * Class to build instances of {@link BucketBlocks}.
     */
    public static class Builder {
        private List<String> bucketBlock;



        /**
         * Setter for bucketBlock.
         * @param  bucketBlock  List of String value for bucketBlock.
         * @return Builder
         */
        public Builder bucketBlock(List<String> bucketBlock) {
            this.bucketBlock = bucketBlock;
            return this;
        }

        /**
         * Builds a new {@link BucketBlocks} object using the set fields.
         * @return {@link BucketBlocks}
         */
        public BucketBlocks build() {
            return new BucketBlocks(bucketBlock);
        }
    }
}
