/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for BusinessOwnerRequest type.
 */
public class BusinessOwnerRequest {
    private Control control;
    private BusinessDetail businessDetails;
    private List<Individual> individuals;
    private TimeAt lengthOwnership;

    /**
     * Default constructor.
     */
    public BusinessOwnerRequest() {
    }

    /**
     * Initialization constructor.
     * @param  control  Control value for control.
     * @param  businessDetails  BusinessDetail value for businessDetails.
     * @param  individuals  List of Individual value for individuals.
     * @param  lengthOwnership  TimeAt value for lengthOwnership.
     */
    public BusinessOwnerRequest(
            Control control,
            BusinessDetail businessDetails,
            List<Individual> individuals,
            TimeAt lengthOwnership) {
        this.control = control;
        this.businessDetails = businessDetails;
        this.individuals = individuals;
        this.lengthOwnership = lengthOwnership;
    }

    /**
     * Getter for Control.
     * @return Returns the Control
     */
    @JsonGetter("Control")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Control getControl() {
        return control;
    }

    /**
     * Setter for Control.
     * @param control Value for Control
     */
    @JsonSetter("Control")
    public void setControl(Control control) {
        this.control = control;
    }

    /**
     * Getter for BusinessDetails.
     * @return Returns the BusinessDetail
     */
    @JsonGetter("BusinessDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BusinessDetail getBusinessDetails() {
        return businessDetails;
    }

    /**
     * Setter for BusinessDetails.
     * @param businessDetails Value for BusinessDetail
     */
    @JsonSetter("BusinessDetails")
    public void setBusinessDetails(BusinessDetail businessDetails) {
        this.businessDetails = businessDetails;
    }

    /**
     * Getter for Individuals.
     * @return Returns the List of Individual
     */
    @JsonGetter("Individuals")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Individual> getIndividuals() {
        return individuals;
    }

    /**
     * Setter for Individuals.
     * @param individuals Value for List of Individual
     */
    @JsonSetter("Individuals")
    public void setIndividuals(List<Individual> individuals) {
        this.individuals = individuals;
    }

    /**
     * Getter for LengthOwnership.
     * @return Returns the TimeAt
     */
    @JsonGetter("LengthOwnership")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TimeAt getLengthOwnership() {
        return lengthOwnership;
    }

    /**
     * Setter for LengthOwnership.
     * @param lengthOwnership Value for TimeAt
     */
    @JsonSetter("LengthOwnership")
    public void setLengthOwnership(TimeAt lengthOwnership) {
        this.lengthOwnership = lengthOwnership;
    }

    /**
     * Converts this BusinessOwnerRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BusinessOwnerRequest [" + "control=" + control + ", businessDetails="
                + businessDetails + ", individuals=" + individuals + ", lengthOwnership="
                + lengthOwnership + "]";
    }

    /**
     * Builds a new {@link BusinessOwnerRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BusinessOwnerRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .control(getControl())
                .businessDetails(getBusinessDetails())
                .individuals(getIndividuals())
                .lengthOwnership(getLengthOwnership());
        return builder;
    }

    /**
     * Class to build instances of {@link BusinessOwnerRequest}.
     */
    public static class Builder {
        private Control control;
        private BusinessDetail businessDetails;
        private List<Individual> individuals;
        private TimeAt lengthOwnership;



        /**
         * Setter for control.
         * @param  control  Control value for control.
         * @return Builder
         */
        public Builder control(Control control) {
            this.control = control;
            return this;
        }

        /**
         * Setter for businessDetails.
         * @param  businessDetails  BusinessDetail value for businessDetails.
         * @return Builder
         */
        public Builder businessDetails(BusinessDetail businessDetails) {
            this.businessDetails = businessDetails;
            return this;
        }

        /**
         * Setter for individuals.
         * @param  individuals  List of Individual value for individuals.
         * @return Builder
         */
        public Builder individuals(List<Individual> individuals) {
            this.individuals = individuals;
            return this;
        }

        /**
         * Setter for lengthOwnership.
         * @param  lengthOwnership  TimeAt value for lengthOwnership.
         * @return Builder
         */
        public Builder lengthOwnership(TimeAt lengthOwnership) {
            this.lengthOwnership = lengthOwnership;
            return this;
        }

        /**
         * Builds a new {@link BusinessOwnerRequest} object using the set fields.
         * @return {@link BusinessOwnerRequest}
         */
        public BusinessOwnerRequest build() {
            return new BusinessOwnerRequest(control, businessDetails, individuals, lengthOwnership);
        }
    }
}
