/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for BusinessOwnerText type.
 */
public class BusinessOwnerText {
    private String concludingText;
    private String creditText;
    private String experianReference;
    private int lengthOfConcludingText;
    private int lengthOfCreditText;
    private int lengthOfNoticeOfCorrectionText;
    private int lengthOfRiskText;
    private String noticeOfCorrectionLength;
    private String riskText;

    /**
     * Default constructor.
     */
    public BusinessOwnerText() {
    }

    /**
     * Initialization constructor.
     * @param  lengthOfConcludingText  int value for lengthOfConcludingText.
     * @param  lengthOfCreditText  int value for lengthOfCreditText.
     * @param  lengthOfNoticeOfCorrectionText  int value for lengthOfNoticeOfCorrectionText.
     * @param  lengthOfRiskText  int value for lengthOfRiskText.
     * @param  concludingText  String value for concludingText.
     * @param  creditText  String value for creditText.
     * @param  experianReference  String value for experianReference.
     * @param  noticeOfCorrectionLength  String value for noticeOfCorrectionLength.
     * @param  riskText  String value for riskText.
     */
    public BusinessOwnerText(
            int lengthOfConcludingText,
            int lengthOfCreditText,
            int lengthOfNoticeOfCorrectionText,
            int lengthOfRiskText,
            String concludingText,
            String creditText,
            String experianReference,
            String noticeOfCorrectionLength,
            String riskText) {
        this.concludingText = concludingText;
        this.creditText = creditText;
        this.experianReference = experianReference;
        this.lengthOfConcludingText = lengthOfConcludingText;
        this.lengthOfCreditText = lengthOfCreditText;
        this.lengthOfNoticeOfCorrectionText = lengthOfNoticeOfCorrectionText;
        this.lengthOfRiskText = lengthOfRiskText;
        this.noticeOfCorrectionLength = noticeOfCorrectionLength;
        this.riskText = riskText;
    }

    /**
     * Getter for ConcludingText.
     * @return Returns the String
     */
    @JsonGetter("ConcludingText")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getConcludingText() {
        return concludingText;
    }

    /**
     * Setter for ConcludingText.
     * @param concludingText Value for String
     */
    @JsonSetter("ConcludingText")
    public void setConcludingText(String concludingText) {
        this.concludingText = concludingText;
    }

    /**
     * Getter for CreditText.
     * @return Returns the String
     */
    @JsonGetter("CreditText")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreditText() {
        return creditText;
    }

    /**
     * Setter for CreditText.
     * @param creditText Value for String
     */
    @JsonSetter("CreditText")
    public void setCreditText(String creditText) {
        this.creditText = creditText;
    }

    /**
     * Getter for ExperianReference.
     * @return Returns the String
     */
    @JsonGetter("ExperianReference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExperianReference() {
        return experianReference;
    }

    /**
     * Setter for ExperianReference.
     * @param experianReference Value for String
     */
    @JsonSetter("ExperianReference")
    public void setExperianReference(String experianReference) {
        this.experianReference = experianReference;
    }

    /**
     * Getter for LengthOfConcludingText.
     * @return Returns the int
     */
    @JsonGetter("LengthOfConcludingText")
    public int getLengthOfConcludingText() {
        return lengthOfConcludingText;
    }

    /**
     * Setter for LengthOfConcludingText.
     * @param lengthOfConcludingText Value for int
     */
    @JsonSetter("LengthOfConcludingText")
    public void setLengthOfConcludingText(int lengthOfConcludingText) {
        this.lengthOfConcludingText = lengthOfConcludingText;
    }

    /**
     * Getter for LengthOfCreditText.
     * @return Returns the int
     */
    @JsonGetter("LengthOfCreditText")
    public int getLengthOfCreditText() {
        return lengthOfCreditText;
    }

    /**
     * Setter for LengthOfCreditText.
     * @param lengthOfCreditText Value for int
     */
    @JsonSetter("LengthOfCreditText")
    public void setLengthOfCreditText(int lengthOfCreditText) {
        this.lengthOfCreditText = lengthOfCreditText;
    }

    /**
     * Getter for LengthOfNoticeOfCorrectionText.
     * @return Returns the int
     */
    @JsonGetter("LengthOfNoticeOfCorrectionText")
    public int getLengthOfNoticeOfCorrectionText() {
        return lengthOfNoticeOfCorrectionText;
    }

    /**
     * Setter for LengthOfNoticeOfCorrectionText.
     * @param lengthOfNoticeOfCorrectionText Value for int
     */
    @JsonSetter("LengthOfNoticeOfCorrectionText")
    public void setLengthOfNoticeOfCorrectionText(int lengthOfNoticeOfCorrectionText) {
        this.lengthOfNoticeOfCorrectionText = lengthOfNoticeOfCorrectionText;
    }

    /**
     * Getter for LengthOfRiskText.
     * @return Returns the int
     */
    @JsonGetter("LengthOfRiskText")
    public int getLengthOfRiskText() {
        return lengthOfRiskText;
    }

    /**
     * Setter for LengthOfRiskText.
     * @param lengthOfRiskText Value for int
     */
    @JsonSetter("LengthOfRiskText")
    public void setLengthOfRiskText(int lengthOfRiskText) {
        this.lengthOfRiskText = lengthOfRiskText;
    }

    /**
     * Getter for NoticeOfCorrectionLength.
     * @return Returns the String
     */
    @JsonGetter("NoticeOfCorrectionLength")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNoticeOfCorrectionLength() {
        return noticeOfCorrectionLength;
    }

    /**
     * Setter for NoticeOfCorrectionLength.
     * @param noticeOfCorrectionLength Value for String
     */
    @JsonSetter("NoticeOfCorrectionLength")
    public void setNoticeOfCorrectionLength(String noticeOfCorrectionLength) {
        this.noticeOfCorrectionLength = noticeOfCorrectionLength;
    }

    /**
     * Getter for RiskText.
     * @return Returns the String
     */
    @JsonGetter("RiskText")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRiskText() {
        return riskText;
    }

    /**
     * Setter for RiskText.
     * @param riskText Value for String
     */
    @JsonSetter("RiskText")
    public void setRiskText(String riskText) {
        this.riskText = riskText;
    }

    /**
     * Converts this BusinessOwnerText into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BusinessOwnerText [" + "lengthOfConcludingText=" + lengthOfConcludingText
                + ", lengthOfCreditText=" + lengthOfCreditText + ", lengthOfNoticeOfCorrectionText="
                + lengthOfNoticeOfCorrectionText + ", lengthOfRiskText=" + lengthOfRiskText
                + ", concludingText=" + concludingText + ", creditText=" + creditText
                + ", experianReference=" + experianReference + ", noticeOfCorrectionLength="
                + noticeOfCorrectionLength + ", riskText=" + riskText + "]";
    }

    /**
     * Builds a new {@link BusinessOwnerText.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BusinessOwnerText.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(lengthOfConcludingText, lengthOfCreditText,
                lengthOfNoticeOfCorrectionText, lengthOfRiskText)
                .concludingText(getConcludingText())
                .creditText(getCreditText())
                .experianReference(getExperianReference())
                .noticeOfCorrectionLength(getNoticeOfCorrectionLength())
                .riskText(getRiskText());
        return builder;
    }

    /**
     * Class to build instances of {@link BusinessOwnerText}.
     */
    public static class Builder {
        private int lengthOfConcludingText;
        private int lengthOfCreditText;
        private int lengthOfNoticeOfCorrectionText;
        private int lengthOfRiskText;
        private String concludingText;
        private String creditText;
        private String experianReference;
        private String noticeOfCorrectionLength;
        private String riskText;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  lengthOfConcludingText  int value for lengthOfConcludingText.
         * @param  lengthOfCreditText  int value for lengthOfCreditText.
         * @param  lengthOfNoticeOfCorrectionText  int value for lengthOfNoticeOfCorrectionText.
         * @param  lengthOfRiskText  int value for lengthOfRiskText.
         */
        public Builder(int lengthOfConcludingText, int lengthOfCreditText,
                int lengthOfNoticeOfCorrectionText, int lengthOfRiskText) {
            this.lengthOfConcludingText = lengthOfConcludingText;
            this.lengthOfCreditText = lengthOfCreditText;
            this.lengthOfNoticeOfCorrectionText = lengthOfNoticeOfCorrectionText;
            this.lengthOfRiskText = lengthOfRiskText;
        }

        /**
         * Setter for lengthOfConcludingText.
         * @param  lengthOfConcludingText  int value for lengthOfConcludingText.
         * @return Builder
         */
        public Builder lengthOfConcludingText(int lengthOfConcludingText) {
            this.lengthOfConcludingText = lengthOfConcludingText;
            return this;
        }

        /**
         * Setter for lengthOfCreditText.
         * @param  lengthOfCreditText  int value for lengthOfCreditText.
         * @return Builder
         */
        public Builder lengthOfCreditText(int lengthOfCreditText) {
            this.lengthOfCreditText = lengthOfCreditText;
            return this;
        }

        /**
         * Setter for lengthOfNoticeOfCorrectionText.
         * @param  lengthOfNoticeOfCorrectionText  int value for lengthOfNoticeOfCorrectionText.
         * @return Builder
         */
        public Builder lengthOfNoticeOfCorrectionText(int lengthOfNoticeOfCorrectionText) {
            this.lengthOfNoticeOfCorrectionText = lengthOfNoticeOfCorrectionText;
            return this;
        }

        /**
         * Setter for lengthOfRiskText.
         * @param  lengthOfRiskText  int value for lengthOfRiskText.
         * @return Builder
         */
        public Builder lengthOfRiskText(int lengthOfRiskText) {
            this.lengthOfRiskText = lengthOfRiskText;
            return this;
        }

        /**
         * Setter for concludingText.
         * @param  concludingText  String value for concludingText.
         * @return Builder
         */
        public Builder concludingText(String concludingText) {
            this.concludingText = concludingText;
            return this;
        }

        /**
         * Setter for creditText.
         * @param  creditText  String value for creditText.
         * @return Builder
         */
        public Builder creditText(String creditText) {
            this.creditText = creditText;
            return this;
        }

        /**
         * Setter for experianReference.
         * @param  experianReference  String value for experianReference.
         * @return Builder
         */
        public Builder experianReference(String experianReference) {
            this.experianReference = experianReference;
            return this;
        }

        /**
         * Setter for noticeOfCorrectionLength.
         * @param  noticeOfCorrectionLength  String value for noticeOfCorrectionLength.
         * @return Builder
         */
        public Builder noticeOfCorrectionLength(String noticeOfCorrectionLength) {
            this.noticeOfCorrectionLength = noticeOfCorrectionLength;
            return this;
        }

        /**
         * Setter for riskText.
         * @param  riskText  String value for riskText.
         * @return Builder
         */
        public Builder riskText(String riskText) {
            this.riskText = riskText;
            return this;
        }

        /**
         * Builds a new {@link BusinessOwnerText} object using the set fields.
         * @return {@link BusinessOwnerText}
         */
        public BusinessOwnerText build() {
            return new BusinessOwnerText(lengthOfConcludingText, lengthOfCreditText,
                    lengthOfNoticeOfCorrectionText, lengthOfRiskText, concludingText, creditText,
                    experianReference, noticeOfCorrectionLength, riskText);
        }
    }
}
