/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for CommissionDetails type.
 */
public class CommissionDetails {
    private String commission;

    /**
     * Default constructor.
     */
    public CommissionDetails() {
    }

    /**
     * Initialization constructor.
     * @param  commission  String value for commission.
     */
    public CommissionDetails(
            String commission) {
        this.commission = commission;
    }

    /**
     * Getter for Commission.
     * A Commission Element for the mortgage for the limited company
     * @return Returns the String
     */
    @JsonGetter("Commission")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCommission() {
        return commission;
    }

    /**
     * Setter for Commission.
     * A Commission Element for the mortgage for the limited company
     * @param commission Value for String
     */
    @JsonSetter("Commission")
    public void setCommission(String commission) {
        this.commission = commission;
    }

    /**
     * Converts this CommissionDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CommissionDetails [" + "commission=" + commission + "]";
    }

    /**
     * Builds a new {@link CommissionDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CommissionDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .commission(getCommission());
        return builder;
    }

    /**
     * Class to build instances of {@link CommissionDetails}.
     */
    public static class Builder {
        private String commission;



        /**
         * Setter for commission.
         * @param  commission  String value for commission.
         * @return Builder
         */
        public Builder commission(String commission) {
            this.commission = commission;
            return this;
        }

        /**
         * Builds a new {@link CommissionDetails} object using the set fields.
         * @return {@link CommissionDetails}
         */
        public CommissionDetails build() {
            return new CommissionDetails(commission);
        }
    }
}
