/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for CompanyHistory type.
 */
public class CompanyHistory {
    private String commDelphiBand;
    private String commDelphiBandText;
    private String commDelphiScore;
    private String overrideIndicator;
    private List<ScoreHistory> scoreHistory;
    private Integer scoreHistoryCount;
    private String stabilityOdds;
    private Integer textCount;

    /**
     * Default constructor.
     */
    public CompanyHistory() {
    }

    /**
     * Initialization constructor.
     * @param  commDelphiBand  String value for commDelphiBand.
     * @param  commDelphiBandText  String value for commDelphiBandText.
     * @param  commDelphiScore  String value for commDelphiScore.
     * @param  overrideIndicator  String value for overrideIndicator.
     * @param  scoreHistory  List of ScoreHistory value for scoreHistory.
     * @param  scoreHistoryCount  Integer value for scoreHistoryCount.
     * @param  stabilityOdds  String value for stabilityOdds.
     * @param  textCount  Integer value for textCount.
     */
    public CompanyHistory(
            String commDelphiBand,
            String commDelphiBandText,
            String commDelphiScore,
            String overrideIndicator,
            List<ScoreHistory> scoreHistory,
            Integer scoreHistoryCount,
            String stabilityOdds,
            Integer textCount) {
        this.commDelphiBand = commDelphiBand;
        this.commDelphiBandText = commDelphiBandText;
        this.commDelphiScore = commDelphiScore;
        this.overrideIndicator = overrideIndicator;
        this.scoreHistory = scoreHistory;
        this.scoreHistoryCount = scoreHistoryCount;
        this.stabilityOdds = stabilityOdds;
        this.textCount = textCount;
    }

    /**
     * Getter for CommDelphiBand.
     * Current Commercial Delphi Band for the limited company
     * @return Returns the String
     */
    @JsonGetter("CommDelphiBand")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCommDelphiBand() {
        return commDelphiBand;
    }

    /**
     * Setter for CommDelphiBand.
     * Current Commercial Delphi Band for the limited company
     * @param commDelphiBand Value for String
     */
    @JsonSetter("CommDelphiBand")
    public void setCommDelphiBand(String commDelphiBand) {
        this.commDelphiBand = commDelphiBand;
    }

    /**
     * Getter for CommDelphiBandText.
     * Current Commercial Delphi Band Text
     * @return Returns the String
     */
    @JsonGetter("CommDelphiBandText")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCommDelphiBandText() {
        return commDelphiBandText;
    }

    /**
     * Setter for CommDelphiBandText.
     * Current Commercial Delphi Band Text
     * @param commDelphiBandText Value for String
     */
    @JsonSetter("CommDelphiBandText")
    public void setCommDelphiBandText(String commDelphiBandText) {
        this.commDelphiBandText = commDelphiBandText;
    }

    /**
     * Getter for CommDelphiScore.
     * Current Commercial Delphi Score for the limited company
     * @return Returns the String
     */
    @JsonGetter("CommDelphiScore")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCommDelphiScore() {
        return commDelphiScore;
    }

    /**
     * Setter for CommDelphiScore.
     * Current Commercial Delphi Score for the limited company
     * @param commDelphiScore Value for String
     */
    @JsonSetter("CommDelphiScore")
    public void setCommDelphiScore(String commDelphiScore) {
        this.commDelphiScore = commDelphiScore;
    }

    /**
     * Getter for OverrideIndicator.
     * Commercial Delphi Score Override indicator - Y = Overridden; N = Not Overridden
     * @return Returns the String
     */
    @JsonGetter("OverrideIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOverrideIndicator() {
        return overrideIndicator;
    }

    /**
     * Setter for OverrideIndicator.
     * Commercial Delphi Score Override indicator - Y = Overridden; N = Not Overridden
     * @param overrideIndicator Value for String
     */
    @JsonSetter("OverrideIndicator")
    public void setOverrideIndicator(String overrideIndicator) {
        this.overrideIndicator = overrideIndicator;
    }

    /**
     * Getter for ScoreHistory.
     * @return Returns the List of ScoreHistory
     */
    @JsonGetter("ScoreHistory")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ScoreHistory> getScoreHistory() {
        return scoreHistory;
    }

    /**
     * Setter for ScoreHistory.
     * @param scoreHistory Value for List of ScoreHistory
     */
    @JsonSetter("ScoreHistory")
    public void setScoreHistory(List<ScoreHistory> scoreHistory) {
        this.scoreHistory = scoreHistory;
    }

    /**
     * Getter for ScoreHistoryCount.
     * Number of instances of Commercial Delphi Score History
     * @return Returns the Integer
     */
    @JsonGetter("ScoreHistoryCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getScoreHistoryCount() {
        return scoreHistoryCount;
    }

    /**
     * Setter for ScoreHistoryCount.
     * Number of instances of Commercial Delphi Score History
     * @param scoreHistoryCount Value for Integer
     */
    @JsonSetter("ScoreHistoryCount")
    public void setScoreHistoryCount(Integer scoreHistoryCount) {
        this.scoreHistoryCount = scoreHistoryCount;
    }

    /**
     * Getter for StabilityOdds.
     * Stability Odds for the limited company
     * @return Returns the String
     */
    @JsonGetter("StabilityOdds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStabilityOdds() {
        return stabilityOdds;
    }

    /**
     * Setter for StabilityOdds.
     * Stability Odds for the limited company
     * @param stabilityOdds Value for String
     */
    @JsonSetter("StabilityOdds")
    public void setStabilityOdds(String stabilityOdds) {
        this.stabilityOdds = stabilityOdds;
    }

    /**
     * Getter for TextCount.
     * Length of text for Commercial Delphi Band Text
     * @return Returns the Integer
     */
    @JsonGetter("TextCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTextCount() {
        return textCount;
    }

    /**
     * Setter for TextCount.
     * Length of text for Commercial Delphi Band Text
     * @param textCount Value for Integer
     */
    @JsonSetter("TextCount")
    public void setTextCount(Integer textCount) {
        this.textCount = textCount;
    }

    /**
     * Converts this CompanyHistory into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CompanyHistory [" + "commDelphiBand=" + commDelphiBand + ", commDelphiBandText="
                + commDelphiBandText + ", commDelphiScore=" + commDelphiScore
                + ", overrideIndicator=" + overrideIndicator + ", scoreHistory=" + scoreHistory
                + ", scoreHistoryCount=" + scoreHistoryCount + ", stabilityOdds=" + stabilityOdds
                + ", textCount=" + textCount + "]";
    }

    /**
     * Builds a new {@link CompanyHistory.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CompanyHistory.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .commDelphiBand(getCommDelphiBand())
                .commDelphiBandText(getCommDelphiBandText())
                .commDelphiScore(getCommDelphiScore())
                .overrideIndicator(getOverrideIndicator())
                .scoreHistory(getScoreHistory())
                .scoreHistoryCount(getScoreHistoryCount())
                .stabilityOdds(getStabilityOdds())
                .textCount(getTextCount());
        return builder;
    }

    /**
     * Class to build instances of {@link CompanyHistory}.
     */
    public static class Builder {
        private String commDelphiBand;
        private String commDelphiBandText;
        private String commDelphiScore;
        private String overrideIndicator;
        private List<ScoreHistory> scoreHistory;
        private Integer scoreHistoryCount;
        private String stabilityOdds;
        private Integer textCount;



        /**
         * Setter for commDelphiBand.
         * @param  commDelphiBand  String value for commDelphiBand.
         * @return Builder
         */
        public Builder commDelphiBand(String commDelphiBand) {
            this.commDelphiBand = commDelphiBand;
            return this;
        }

        /**
         * Setter for commDelphiBandText.
         * @param  commDelphiBandText  String value for commDelphiBandText.
         * @return Builder
         */
        public Builder commDelphiBandText(String commDelphiBandText) {
            this.commDelphiBandText = commDelphiBandText;
            return this;
        }

        /**
         * Setter for commDelphiScore.
         * @param  commDelphiScore  String value for commDelphiScore.
         * @return Builder
         */
        public Builder commDelphiScore(String commDelphiScore) {
            this.commDelphiScore = commDelphiScore;
            return this;
        }

        /**
         * Setter for overrideIndicator.
         * @param  overrideIndicator  String value for overrideIndicator.
         * @return Builder
         */
        public Builder overrideIndicator(String overrideIndicator) {
            this.overrideIndicator = overrideIndicator;
            return this;
        }

        /**
         * Setter for scoreHistory.
         * @param  scoreHistory  List of ScoreHistory value for scoreHistory.
         * @return Builder
         */
        public Builder scoreHistory(List<ScoreHistory> scoreHistory) {
            this.scoreHistory = scoreHistory;
            return this;
        }

        /**
         * Setter for scoreHistoryCount.
         * @param  scoreHistoryCount  Integer value for scoreHistoryCount.
         * @return Builder
         */
        public Builder scoreHistoryCount(Integer scoreHistoryCount) {
            this.scoreHistoryCount = scoreHistoryCount;
            return this;
        }

        /**
         * Setter for stabilityOdds.
         * @param  stabilityOdds  String value for stabilityOdds.
         * @return Builder
         */
        public Builder stabilityOdds(String stabilityOdds) {
            this.stabilityOdds = stabilityOdds;
            return this;
        }

        /**
         * Setter for textCount.
         * @param  textCount  Integer value for textCount.
         * @return Builder
         */
        public Builder textCount(Integer textCount) {
            this.textCount = textCount;
            return this;
        }

        /**
         * Builds a new {@link CompanyHistory} object using the set fields.
         * @return {@link CompanyHistory}
         */
        public CompanyHistory build() {
            return new CompanyHistory(commDelphiBand, commDelphiBandText, commDelphiScore,
                    overrideIndicator, scoreHistory, scoreHistoryCount, stabilityOdds, textCount);
        }
    }
}
