/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for DebitMonthly type.
 */
public class DebitMonthly {
    private String expMonth;
    private Integer dBT;
    private Integer numExp;

    /**
     * Default constructor.
     */
    public DebitMonthly() {
    }

    /**
     * Initialization constructor.
     * @param  expMonth  String value for expMonth.
     * @param  dBT  Integer value for dBT.
     * @param  numExp  Integer value for numExp.
     */
    public DebitMonthly(
            String expMonth,
            Integer dBT,
            Integer numExp) {
        this.expMonth = expMonth;
        this.dBT = dBT;
        this.numExp = numExp;
    }

    /**
     * Getter for ExpMonth.
     * DBT experience month (yyyy-mm)
     * @return Returns the String
     */
    @JsonGetter("ExpMonth")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExpMonth() {
        return expMonth;
    }

    /**
     * Setter for ExpMonth.
     * DBT experience month (yyyy-mm)
     * @param expMonth Value for String
     */
    @JsonSetter("ExpMonth")
    public void setExpMonth(String expMonth) {
        this.expMonth = expMonth;
    }

    /**
     * Getter for DBT.
     * Days beyond terms for payment experience for the experience month for the non-limited
     * business
     * @return Returns the Integer
     */
    @JsonGetter("DBT")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDBT() {
        return dBT;
    }

    /**
     * Setter for DBT.
     * Days beyond terms for payment experience for the experience month for the non-limited
     * business
     * @param dBT Value for Integer
     */
    @JsonSetter("DBT")
    public void setDBT(Integer dBT) {
        this.dBT = dBT;
    }

    /**
     * Getter for NumExp.
     * Number of experiences for days beyond terms for payment experience for the experience month
     * for the non-limited business
     * @return Returns the Integer
     */
    @JsonGetter("NumExp")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumExp() {
        return numExp;
    }

    /**
     * Setter for NumExp.
     * Number of experiences for days beyond terms for payment experience for the experience month
     * for the non-limited business
     * @param numExp Value for Integer
     */
    @JsonSetter("NumExp")
    public void setNumExp(Integer numExp) {
        this.numExp = numExp;
    }

    /**
     * Converts this DebitMonthly into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DebitMonthly [" + "expMonth=" + expMonth + ", dBT=" + dBT + ", numExp=" + numExp
                + "]";
    }

    /**
     * Builds a new {@link DebitMonthly.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DebitMonthly.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .expMonth(getExpMonth())
                .dBT(getDBT())
                .numExp(getNumExp());
        return builder;
    }

    /**
     * Class to build instances of {@link DebitMonthly}.
     */
    public static class Builder {
        private String expMonth;
        private Integer dBT;
        private Integer numExp;



        /**
         * Setter for expMonth.
         * @param  expMonth  String value for expMonth.
         * @return Builder
         */
        public Builder expMonth(String expMonth) {
            this.expMonth = expMonth;
            return this;
        }

        /**
         * Setter for dBT.
         * @param  dBT  Integer value for dBT.
         * @return Builder
         */
        public Builder dBT(Integer dBT) {
            this.dBT = dBT;
            return this;
        }

        /**
         * Setter for numExp.
         * @param  numExp  Integer value for numExp.
         * @return Builder
         */
        public Builder numExp(Integer numExp) {
            this.numExp = numExp;
            return this;
        }

        /**
         * Builds a new {@link DebitMonthly} object using the set fields.
         * @return {@link DebitMonthly}
         */
        public DebitMonthly build() {
            return new DebitMonthly(expMonth, dBT, numExp);
        }
    }
}
