/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for Directorships type.
 */
public class Directorships {
    private List<IndvDirCurrDirectorship> currentDirector;
    private List<IndvDirPrevDirectorship> previousDirector;
    private List<IndvDirCurrDisslvdDirectorship> currentDissolvedDirector;
    private List<IndvDirPrevDisslvdDirectorship> previousDissolvedDirector;

    /**
     * Default constructor.
     */
    public Directorships() {
    }

    /**
     * Initialization constructor.
     * @param  currentDirector  List of IndvDirCurrDirectorship value for currentDirector.
     * @param  previousDirector  List of IndvDirPrevDirectorship value for previousDirector.
     * @param  currentDissolvedDirector  List of IndvDirCurrDisslvdDirectorship value for
     *         currentDissolvedDirector.
     * @param  previousDissolvedDirector  List of IndvDirPrevDisslvdDirectorship value for
     *         previousDissolvedDirector.
     */
    public Directorships(
            List<IndvDirCurrDirectorship> currentDirector,
            List<IndvDirPrevDirectorship> previousDirector,
            List<IndvDirCurrDisslvdDirectorship> currentDissolvedDirector,
            List<IndvDirPrevDisslvdDirectorship> previousDissolvedDirector) {
        this.currentDirector = currentDirector;
        this.previousDirector = previousDirector;
        this.currentDissolvedDirector = currentDissolvedDirector;
        this.previousDissolvedDirector = previousDissolvedDirector;
    }

    /**
     * Getter for CurrentDirector.
     * @return Returns the List of IndvDirCurrDirectorship
     */
    @JsonGetter("CurrentDirector")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<IndvDirCurrDirectorship> getCurrentDirector() {
        return currentDirector;
    }

    /**
     * Setter for CurrentDirector.
     * @param currentDirector Value for List of IndvDirCurrDirectorship
     */
    @JsonSetter("CurrentDirector")
    public void setCurrentDirector(List<IndvDirCurrDirectorship> currentDirector) {
        this.currentDirector = currentDirector;
    }

    /**
     * Getter for PreviousDirector.
     * @return Returns the List of IndvDirPrevDirectorship
     */
    @JsonGetter("PreviousDirector")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<IndvDirPrevDirectorship> getPreviousDirector() {
        return previousDirector;
    }

    /**
     * Setter for PreviousDirector.
     * @param previousDirector Value for List of IndvDirPrevDirectorship
     */
    @JsonSetter("PreviousDirector")
    public void setPreviousDirector(List<IndvDirPrevDirectorship> previousDirector) {
        this.previousDirector = previousDirector;
    }

    /**
     * Getter for CurrentDissolvedDirector.
     * @return Returns the List of IndvDirCurrDisslvdDirectorship
     */
    @JsonGetter("CurrentDissolvedDirector")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<IndvDirCurrDisslvdDirectorship> getCurrentDissolvedDirector() {
        return currentDissolvedDirector;
    }

    /**
     * Setter for CurrentDissolvedDirector.
     * @param currentDissolvedDirector Value for List of IndvDirCurrDisslvdDirectorship
     */
    @JsonSetter("CurrentDissolvedDirector")
    public void setCurrentDissolvedDirector(List<IndvDirCurrDisslvdDirectorship> currentDissolvedDirector) {
        this.currentDissolvedDirector = currentDissolvedDirector;
    }

    /**
     * Getter for PreviousDissolvedDirector.
     * @return Returns the List of IndvDirPrevDisslvdDirectorship
     */
    @JsonGetter("PreviousDissolvedDirector")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<IndvDirPrevDisslvdDirectorship> getPreviousDissolvedDirector() {
        return previousDissolvedDirector;
    }

    /**
     * Setter for PreviousDissolvedDirector.
     * @param previousDissolvedDirector Value for List of IndvDirPrevDisslvdDirectorship
     */
    @JsonSetter("PreviousDissolvedDirector")
    public void setPreviousDissolvedDirector(List<IndvDirPrevDisslvdDirectorship> previousDissolvedDirector) {
        this.previousDissolvedDirector = previousDissolvedDirector;
    }

    /**
     * Converts this Directorships into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Directorships [" + "currentDirector=" + currentDirector + ", previousDirector="
                + previousDirector + ", currentDissolvedDirector=" + currentDissolvedDirector
                + ", previousDissolvedDirector=" + previousDissolvedDirector + "]";
    }

    /**
     * Builds a new {@link Directorships.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Directorships.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .currentDirector(getCurrentDirector())
                .previousDirector(getPreviousDirector())
                .currentDissolvedDirector(getCurrentDissolvedDirector())
                .previousDissolvedDirector(getPreviousDissolvedDirector());
        return builder;
    }

    /**
     * Class to build instances of {@link Directorships}.
     */
    public static class Builder {
        private List<IndvDirCurrDirectorship> currentDirector;
        private List<IndvDirPrevDirectorship> previousDirector;
        private List<IndvDirCurrDisslvdDirectorship> currentDissolvedDirector;
        private List<IndvDirPrevDisslvdDirectorship> previousDissolvedDirector;



        /**
         * Setter for currentDirector.
         * @param  currentDirector  List of IndvDirCurrDirectorship value for currentDirector.
         * @return Builder
         */
        public Builder currentDirector(List<IndvDirCurrDirectorship> currentDirector) {
            this.currentDirector = currentDirector;
            return this;
        }

        /**
         * Setter for previousDirector.
         * @param  previousDirector  List of IndvDirPrevDirectorship value for previousDirector.
         * @return Builder
         */
        public Builder previousDirector(List<IndvDirPrevDirectorship> previousDirector) {
            this.previousDirector = previousDirector;
            return this;
        }

        /**
         * Setter for currentDissolvedDirector.
         * @param  currentDissolvedDirector  List of IndvDirCurrDisslvdDirectorship value for
         *         currentDissolvedDirector.
         * @return Builder
         */
        public Builder currentDissolvedDirector(
                List<IndvDirCurrDisslvdDirectorship> currentDissolvedDirector) {
            this.currentDissolvedDirector = currentDissolvedDirector;
            return this;
        }

        /**
         * Setter for previousDissolvedDirector.
         * @param  previousDissolvedDirector  List of IndvDirPrevDisslvdDirectorship value for
         *         previousDissolvedDirector.
         * @return Builder
         */
        public Builder previousDissolvedDirector(
                List<IndvDirPrevDisslvdDirectorship> previousDissolvedDirector) {
            this.previousDissolvedDirector = previousDissolvedDirector;
            return this;
        }

        /**
         * Builds a new {@link Directorships} object using the set fields.
         * @return {@link Directorships}
         */
        public Directorships build() {
            return new Directorships(currentDirector, previousDirector, currentDissolvedDirector,
                    previousDissolvedDirector);
        }
    }
}
