/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for DirPreviousAddr type.
 */
public class DirPreviousAddr {
    private String dateChanged;
    private String foreignAddressFlag;
    private OutputDirLocationDetail location;

    /**
     * Default constructor.
     */
    public DirPreviousAddr() {
    }

    /**
     * Initialization constructor.
     * @param  dateChanged  String value for dateChanged.
     * @param  foreignAddressFlag  String value for foreignAddressFlag.
     * @param  location  OutputDirLocationDetail value for location.
     */
    public DirPreviousAddr(
            String dateChanged,
            String foreignAddressFlag,
            OutputDirLocationDetail location) {
        this.dateChanged = dateChanged;
        this.foreignAddressFlag = foreignAddressFlag;
        this.location = location;
    }

    /**
     * Getter for DateChanged.
     * Address date change (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("DateChanged")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDateChanged() {
        return dateChanged;
    }

    /**
     * Setter for DateChanged.
     * Address date change (yyyy-mm-dd)
     * @param dateChanged Value for String
     */
    @JsonSetter("DateChanged")
    public void setDateChanged(String dateChanged) {
        this.dateChanged = dateChanged;
    }

    /**
     * Getter for ForeignAddressFlag.
     * Indicator showing whether the person's previous address is foreign - N=UK address, Y=Foreign
     * Address, M=Unknown address
     * @return Returns the String
     */
    @JsonGetter("ForeignAddressFlag")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getForeignAddressFlag() {
        return foreignAddressFlag;
    }

    /**
     * Setter for ForeignAddressFlag.
     * Indicator showing whether the person's previous address is foreign - N=UK address, Y=Foreign
     * Address, M=Unknown address
     * @param foreignAddressFlag Value for String
     */
    @JsonSetter("ForeignAddressFlag")
    public void setForeignAddressFlag(String foreignAddressFlag) {
        this.foreignAddressFlag = foreignAddressFlag;
    }

    /**
     * Getter for Location.
     * @return Returns the OutputDirLocationDetail
     */
    @JsonGetter("Location")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public OutputDirLocationDetail getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * @param location Value for OutputDirLocationDetail
     */
    @JsonSetter("Location")
    public void setLocation(OutputDirLocationDetail location) {
        this.location = location;
    }

    /**
     * Converts this DirPreviousAddr into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DirPreviousAddr [" + "dateChanged=" + dateChanged + ", foreignAddressFlag="
                + foreignAddressFlag + ", location=" + location + "]";
    }

    /**
     * Builds a new {@link DirPreviousAddr.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DirPreviousAddr.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .dateChanged(getDateChanged())
                .foreignAddressFlag(getForeignAddressFlag())
                .location(getLocation());
        return builder;
    }

    /**
     * Class to build instances of {@link DirPreviousAddr}.
     */
    public static class Builder {
        private String dateChanged;
        private String foreignAddressFlag;
        private OutputDirLocationDetail location;



        /**
         * Setter for dateChanged.
         * @param  dateChanged  String value for dateChanged.
         * @return Builder
         */
        public Builder dateChanged(String dateChanged) {
            this.dateChanged = dateChanged;
            return this;
        }

        /**
         * Setter for foreignAddressFlag.
         * @param  foreignAddressFlag  String value for foreignAddressFlag.
         * @return Builder
         */
        public Builder foreignAddressFlag(String foreignAddressFlag) {
            this.foreignAddressFlag = foreignAddressFlag;
            return this;
        }

        /**
         * Setter for location.
         * @param  location  OutputDirLocationDetail value for location.
         * @return Builder
         */
        public Builder location(OutputDirLocationDetail location) {
            this.location = location;
            return this;
        }

        /**
         * Builds a new {@link DirPreviousAddr} object using the set fields.
         * @return {@link DirPreviousAddr}
         */
        public DirPreviousAddr build() {
            return new DirPreviousAddr(dateChanged, foreignAddressFlag, location);
        }
    }
}
