/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for Identification type.
 */
public class Identification {
    private String earliestKnownDate;
    private String lastUpdated;
    private Integer num1992SICCodes;
    private NonLtdBusinessLocation businessLocation;
    private String telephoneNumber;
    private String principalActivities;
    private List<SICInfo92> sICInformation1992;
    private Double avgNumEmployees;
    private Integer numTelephone;
    private Integer numFax;
    private List<TelephoneDetails> telephone;
    private List<FaxDetails> fax;
    private ThomsonData thomsonData;
    private PrevSearches prevSearches;
    private ConsumerCreditLicenceSummary consumerCreditLicenceSummary;
    private ArrayOfCCLDetail cCLs;

    /**
     * Default constructor.
     */
    public Identification() {
    }

    /**
     * Initialization constructor.
     * @param  earliestKnownDate  String value for earliestKnownDate.
     * @param  lastUpdated  String value for lastUpdated.
     * @param  num1992SICCodes  Integer value for num1992SICCodes.
     * @param  businessLocation  NonLtdBusinessLocation value for businessLocation.
     * @param  telephoneNumber  String value for telephoneNumber.
     * @param  principalActivities  String value for principalActivities.
     * @param  sICInformation1992  List of SICInfo92 value for sICInformation1992.
     * @param  avgNumEmployees  Double value for avgNumEmployees.
     * @param  numTelephone  Integer value for numTelephone.
     * @param  numFax  Integer value for numFax.
     * @param  telephone  List of TelephoneDetails value for telephone.
     * @param  fax  List of FaxDetails value for fax.
     * @param  thomsonData  ThomsonData value for thomsonData.
     * @param  prevSearches  PrevSearches value for prevSearches.
     * @param  consumerCreditLicenceSummary  ConsumerCreditLicenceSummary value for
     *         consumerCreditLicenceSummary.
     * @param  cCLs  ArrayOfCCLDetail value for cCLs.
     */
    public Identification(
            String earliestKnownDate,
            String lastUpdated,
            Integer num1992SICCodes,
            NonLtdBusinessLocation businessLocation,
            String telephoneNumber,
            String principalActivities,
            List<SICInfo92> sICInformation1992,
            Double avgNumEmployees,
            Integer numTelephone,
            Integer numFax,
            List<TelephoneDetails> telephone,
            List<FaxDetails> fax,
            ThomsonData thomsonData,
            PrevSearches prevSearches,
            ConsumerCreditLicenceSummary consumerCreditLicenceSummary,
            ArrayOfCCLDetail cCLs) {
        this.earliestKnownDate = earliestKnownDate;
        this.lastUpdated = lastUpdated;
        this.num1992SICCodes = num1992SICCodes;
        this.businessLocation = businessLocation;
        this.telephoneNumber = telephoneNumber;
        this.principalActivities = principalActivities;
        this.sICInformation1992 = sICInformation1992;
        this.avgNumEmployees = avgNumEmployees;
        this.numTelephone = numTelephone;
        this.numFax = numFax;
        this.telephone = telephone;
        this.fax = fax;
        this.thomsonData = thomsonData;
        this.prevSearches = prevSearches;
        this.consumerCreditLicenceSummary = consumerCreditLicenceSummary;
        this.cCLs = cCLs;
    }

    /**
     * Getter for EarliestKnownDate.
     * The earliest date when this non-limited business became known to Experian (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("EarliestKnownDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEarliestKnownDate() {
        return earliestKnownDate;
    }

    /**
     * Setter for EarliestKnownDate.
     * The earliest date when this non-limited business became known to Experian (yyyy-mm-dd)
     * @param earliestKnownDate Value for String
     */
    @JsonSetter("EarliestKnownDate")
    public void setEarliestKnownDate(String earliestKnownDate) {
        this.earliestKnownDate = earliestKnownDate;
    }

    /**
     * Getter for LastUpdated.
     * The date of latest update (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("LastUpdated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Setter for LastUpdated.
     * The date of latest update (yyyy-mm-dd)
     * @param lastUpdated Value for String
     */
    @JsonSetter("LastUpdated")
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * Getter for Num1992SICCodes.
     * The number of 1992 SIC Codes held for the non limited business (max 10)
     * @return Returns the Integer
     */
    @JsonGetter("Num1992SICCodes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNum1992SICCodes() {
        return num1992SICCodes;
    }

    /**
     * Setter for Num1992SICCodes.
     * The number of 1992 SIC Codes held for the non limited business (max 10)
     * @param num1992SICCodes Value for Integer
     */
    @JsonSetter("Num1992SICCodes")
    public void setNum1992SICCodes(Integer num1992SICCodes) {
        this.num1992SICCodes = num1992SICCodes;
    }

    /**
     * Getter for BusinessLocation.
     * @return Returns the NonLtdBusinessLocation
     */
    @JsonGetter("BusinessLocation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public NonLtdBusinessLocation getBusinessLocation() {
        return businessLocation;
    }

    /**
     * Setter for BusinessLocation.
     * @param businessLocation Value for NonLtdBusinessLocation
     */
    @JsonSetter("BusinessLocation")
    public void setBusinessLocation(NonLtdBusinessLocation businessLocation) {
        this.businessLocation = businessLocation;
    }

    /**
     * Getter for TelephoneNumber.
     * Non-limited business telephone number
     * @return Returns the String
     */
    @JsonGetter("TelephoneNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Setter for TelephoneNumber.
     * Non-limited business telephone number
     * @param telephoneNumber Value for String
     */
    @JsonSetter("TelephoneNumber")
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    /**
     * Getter for PrincipalActivities.
     * Principle activities for the non-limited business
     * @return Returns the String
     */
    @JsonGetter("PrincipalActivities")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrincipalActivities() {
        return principalActivities;
    }

    /**
     * Setter for PrincipalActivities.
     * Principle activities for the non-limited business
     * @param principalActivities Value for String
     */
    @JsonSetter("PrincipalActivities")
    public void setPrincipalActivities(String principalActivities) {
        this.principalActivities = principalActivities;
    }

    /**
     * Getter for SICInformation1992.
     * @return Returns the List of SICInfo92
     */
    @JsonGetter("SICInformation1992")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SICInfo92> getSICInformation1992() {
        return sICInformation1992;
    }

    /**
     * Setter for SICInformation1992.
     * @param sICInformation1992 Value for List of SICInfo92
     */
    @JsonSetter("SICInformation1992")
    public void setSICInformation1992(List<SICInfo92> sICInformation1992) {
        this.sICInformation1992 = sICInformation1992;
    }

    /**
     * Getter for AvgNumEmployees.
     * The average number of employees for the non-limited business
     * @return Returns the Double
     */
    @JsonGetter("AvgNumEmployees")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAvgNumEmployees() {
        return avgNumEmployees;
    }

    /**
     * Setter for AvgNumEmployees.
     * The average number of employees for the non-limited business
     * @param avgNumEmployees Value for Double
     */
    @JsonSetter("AvgNumEmployees")
    public void setAvgNumEmployees(Double avgNumEmployees) {
        this.avgNumEmployees = avgNumEmployees;
    }

    /**
     * Getter for NumTelephone.
     * The number of telephone numbers held for the non-limited business
     * @return Returns the Integer
     */
    @JsonGetter("NumTelephone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumTelephone() {
        return numTelephone;
    }

    /**
     * Setter for NumTelephone.
     * The number of telephone numbers held for the non-limited business
     * @param numTelephone Value for Integer
     */
    @JsonSetter("NumTelephone")
    public void setNumTelephone(Integer numTelephone) {
        this.numTelephone = numTelephone;
    }

    /**
     * Getter for NumFax.
     * The number of fax numbers held for the non-limited business
     * @return Returns the Integer
     */
    @JsonGetter("NumFax")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getNumFax() {
        return numFax;
    }

    /**
     * Setter for NumFax.
     * The number of fax numbers held for the non-limited business
     * @param numFax Value for Integer
     */
    @JsonSetter("NumFax")
    public void setNumFax(Integer numFax) {
        this.numFax = numFax;
    }

    /**
     * Getter for Telephone.
     * @return Returns the List of TelephoneDetails
     */
    @JsonGetter("Telephone")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<TelephoneDetails> getTelephone() {
        return telephone;
    }

    /**
     * Setter for Telephone.
     * @param telephone Value for List of TelephoneDetails
     */
    @JsonSetter("Telephone")
    public void setTelephone(List<TelephoneDetails> telephone) {
        this.telephone = telephone;
    }

    /**
     * Getter for Fax.
     * @return Returns the List of FaxDetails
     */
    @JsonGetter("Fax")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<FaxDetails> getFax() {
        return fax;
    }

    /**
     * Setter for Fax.
     * @param fax Value for List of FaxDetails
     */
    @JsonSetter("Fax")
    public void setFax(List<FaxDetails> fax) {
        this.fax = fax;
    }

    /**
     * Getter for ThomsonData.
     * @return Returns the ThomsonData
     */
    @JsonGetter("ThomsonData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThomsonData getThomsonData() {
        return thomsonData;
    }

    /**
     * Setter for ThomsonData.
     * @param thomsonData Value for ThomsonData
     */
    @JsonSetter("ThomsonData")
    public void setThomsonData(ThomsonData thomsonData) {
        this.thomsonData = thomsonData;
    }

    /**
     * Getter for PrevSearches.
     * @return Returns the PrevSearches
     */
    @JsonGetter("PrevSearches")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PrevSearches getPrevSearches() {
        return prevSearches;
    }

    /**
     * Setter for PrevSearches.
     * @param prevSearches Value for PrevSearches
     */
    @JsonSetter("PrevSearches")
    public void setPrevSearches(PrevSearches prevSearches) {
        this.prevSearches = prevSearches;
    }

    /**
     * Getter for ConsumerCreditLicenceSummary.
     * @return Returns the ConsumerCreditLicenceSummary
     */
    @JsonGetter("ConsumerCreditLicenceSummary")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ConsumerCreditLicenceSummary getConsumerCreditLicenceSummary() {
        return consumerCreditLicenceSummary;
    }

    /**
     * Setter for ConsumerCreditLicenceSummary.
     * @param consumerCreditLicenceSummary Value for ConsumerCreditLicenceSummary
     */
    @JsonSetter("ConsumerCreditLicenceSummary")
    public void setConsumerCreditLicenceSummary(ConsumerCreditLicenceSummary consumerCreditLicenceSummary) {
        this.consumerCreditLicenceSummary = consumerCreditLicenceSummary;
    }

    /**
     * Getter for CCLs.
     * @return Returns the ArrayOfCCLDetail
     */
    @JsonGetter("CCLs")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ArrayOfCCLDetail getCCLs() {
        return cCLs;
    }

    /**
     * Setter for CCLs.
     * @param cCLs Value for ArrayOfCCLDetail
     */
    @JsonSetter("CCLs")
    public void setCCLs(ArrayOfCCLDetail cCLs) {
        this.cCLs = cCLs;
    }

    /**
     * Converts this Identification into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Identification [" + "earliestKnownDate=" + earliestKnownDate + ", lastUpdated="
                + lastUpdated + ", num1992SICCodes=" + num1992SICCodes + ", businessLocation="
                + businessLocation + ", telephoneNumber=" + telephoneNumber
                + ", principalActivities=" + principalActivities + ", sICInformation1992="
                + sICInformation1992 + ", avgNumEmployees=" + avgNumEmployees + ", numTelephone="
                + numTelephone + ", numFax=" + numFax + ", telephone=" + telephone + ", fax=" + fax
                + ", thomsonData=" + thomsonData + ", prevSearches=" + prevSearches
                + ", consumerCreditLicenceSummary=" + consumerCreditLicenceSummary + ", cCLs="
                + cCLs + "]";
    }

    /**
     * Builds a new {@link Identification.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Identification.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .earliestKnownDate(getEarliestKnownDate())
                .lastUpdated(getLastUpdated())
                .num1992SICCodes(getNum1992SICCodes())
                .businessLocation(getBusinessLocation())
                .telephoneNumber(getTelephoneNumber())
                .principalActivities(getPrincipalActivities())
                .sICInformation1992(getSICInformation1992())
                .avgNumEmployees(getAvgNumEmployees())
                .numTelephone(getNumTelephone())
                .numFax(getNumFax())
                .telephone(getTelephone())
                .fax(getFax())
                .thomsonData(getThomsonData())
                .prevSearches(getPrevSearches())
                .consumerCreditLicenceSummary(getConsumerCreditLicenceSummary())
                .cCLs(getCCLs());
        return builder;
    }

    /**
     * Class to build instances of {@link Identification}.
     */
    public static class Builder {
        private String earliestKnownDate;
        private String lastUpdated;
        private Integer num1992SICCodes;
        private NonLtdBusinessLocation businessLocation;
        private String telephoneNumber;
        private String principalActivities;
        private List<SICInfo92> sICInformation1992;
        private Double avgNumEmployees;
        private Integer numTelephone;
        private Integer numFax;
        private List<TelephoneDetails> telephone;
        private List<FaxDetails> fax;
        private ThomsonData thomsonData;
        private PrevSearches prevSearches;
        private ConsumerCreditLicenceSummary consumerCreditLicenceSummary;
        private ArrayOfCCLDetail cCLs;



        /**
         * Setter for earliestKnownDate.
         * @param  earliestKnownDate  String value for earliestKnownDate.
         * @return Builder
         */
        public Builder earliestKnownDate(String earliestKnownDate) {
            this.earliestKnownDate = earliestKnownDate;
            return this;
        }

        /**
         * Setter for lastUpdated.
         * @param  lastUpdated  String value for lastUpdated.
         * @return Builder
         */
        public Builder lastUpdated(String lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        /**
         * Setter for num1992SICCodes.
         * @param  num1992SICCodes  Integer value for num1992SICCodes.
         * @return Builder
         */
        public Builder num1992SICCodes(Integer num1992SICCodes) {
            this.num1992SICCodes = num1992SICCodes;
            return this;
        }

        /**
         * Setter for businessLocation.
         * @param  businessLocation  NonLtdBusinessLocation value for businessLocation.
         * @return Builder
         */
        public Builder businessLocation(NonLtdBusinessLocation businessLocation) {
            this.businessLocation = businessLocation;
            return this;
        }

        /**
         * Setter for telephoneNumber.
         * @param  telephoneNumber  String value for telephoneNumber.
         * @return Builder
         */
        public Builder telephoneNumber(String telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
            return this;
        }

        /**
         * Setter for principalActivities.
         * @param  principalActivities  String value for principalActivities.
         * @return Builder
         */
        public Builder principalActivities(String principalActivities) {
            this.principalActivities = principalActivities;
            return this;
        }

        /**
         * Setter for sICInformation1992.
         * @param  sICInformation1992  List of SICInfo92 value for sICInformation1992.
         * @return Builder
         */
        public Builder sICInformation1992(List<SICInfo92> sICInformation1992) {
            this.sICInformation1992 = sICInformation1992;
            return this;
        }

        /**
         * Setter for avgNumEmployees.
         * @param  avgNumEmployees  Double value for avgNumEmployees.
         * @return Builder
         */
        public Builder avgNumEmployees(Double avgNumEmployees) {
            this.avgNumEmployees = avgNumEmployees;
            return this;
        }

        /**
         * Setter for numTelephone.
         * @param  numTelephone  Integer value for numTelephone.
         * @return Builder
         */
        public Builder numTelephone(Integer numTelephone) {
            this.numTelephone = numTelephone;
            return this;
        }

        /**
         * Setter for numFax.
         * @param  numFax  Integer value for numFax.
         * @return Builder
         */
        public Builder numFax(Integer numFax) {
            this.numFax = numFax;
            return this;
        }

        /**
         * Setter for telephone.
         * @param  telephone  List of TelephoneDetails value for telephone.
         * @return Builder
         */
        public Builder telephone(List<TelephoneDetails> telephone) {
            this.telephone = telephone;
            return this;
        }

        /**
         * Setter for fax.
         * @param  fax  List of FaxDetails value for fax.
         * @return Builder
         */
        public Builder fax(List<FaxDetails> fax) {
            this.fax = fax;
            return this;
        }

        /**
         * Setter for thomsonData.
         * @param  thomsonData  ThomsonData value for thomsonData.
         * @return Builder
         */
        public Builder thomsonData(ThomsonData thomsonData) {
            this.thomsonData = thomsonData;
            return this;
        }

        /**
         * Setter for prevSearches.
         * @param  prevSearches  PrevSearches value for prevSearches.
         * @return Builder
         */
        public Builder prevSearches(PrevSearches prevSearches) {
            this.prevSearches = prevSearches;
            return this;
        }

        /**
         * Setter for consumerCreditLicenceSummary.
         * @param  consumerCreditLicenceSummary  ConsumerCreditLicenceSummary value for
         *         consumerCreditLicenceSummary.
         * @return Builder
         */
        public Builder consumerCreditLicenceSummary(
                ConsumerCreditLicenceSummary consumerCreditLicenceSummary) {
            this.consumerCreditLicenceSummary = consumerCreditLicenceSummary;
            return this;
        }

        /**
         * Setter for cCLs.
         * @param  cCLs  ArrayOfCCLDetail value for cCLs.
         * @return Builder
         */
        public Builder cCLs(ArrayOfCCLDetail cCLs) {
            this.cCLs = cCLs;
            return this;
        }

        /**
         * Builds a new {@link Identification} object using the set fields.
         * @return {@link Identification}
         */
        public Identification build() {
            return new Identification(earliestKnownDate, lastUpdated, num1992SICCodes,
                    businessLocation, telephoneNumber, principalActivities, sICInformation1992,
                    avgNumEmployees, numTelephone, numFax, telephone, fax, thomsonData,
                    prevSearches, consumerCreditLicenceSummary, cCLs);
        }
    }
}
