/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IndividualResponse type.
 */
public class IndividualResponse {
    private CurrentAddress currentAddress;
    private String sequenceNumber;

    /**
     * Default constructor.
     */
    public IndividualResponse() {
    }

    /**
     * Initialization constructor.
     * @param  currentAddress  CurrentAddress value for currentAddress.
     * @param  sequenceNumber  String value for sequenceNumber.
     */
    public IndividualResponse(
            CurrentAddress currentAddress,
            String sequenceNumber) {
        this.currentAddress = currentAddress;
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * Getter for CurrentAddress.
     * @return Returns the CurrentAddress
     */
    @JsonGetter("CurrentAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CurrentAddress getCurrentAddress() {
        return currentAddress;
    }

    /**
     * Setter for CurrentAddress.
     * @param currentAddress Value for CurrentAddress
     */
    @JsonSetter("CurrentAddress")
    public void setCurrentAddress(CurrentAddress currentAddress) {
        this.currentAddress = currentAddress;
    }

    /**
     * Getter for SequenceNumber.
     * @return Returns the String
     */
    @JsonGetter("SequenceNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Setter for SequenceNumber.
     * @param sequenceNumber Value for String
     */
    @JsonSetter("SequenceNumber")
    public void setSequenceNumber(String sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * Converts this IndividualResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IndividualResponse [" + "currentAddress=" + currentAddress + ", sequenceNumber="
                + sequenceNumber + "]";
    }

    /**
     * Builds a new {@link IndividualResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IndividualResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .currentAddress(getCurrentAddress())
                .sequenceNumber(getSequenceNumber());
        return builder;
    }

    /**
     * Class to build instances of {@link IndividualResponse}.
     */
    public static class Builder {
        private CurrentAddress currentAddress;
        private String sequenceNumber;



        /**
         * Setter for currentAddress.
         * @param  currentAddress  CurrentAddress value for currentAddress.
         * @return Builder
         */
        public Builder currentAddress(CurrentAddress currentAddress) {
            this.currentAddress = currentAddress;
            return this;
        }

        /**
         * Setter for sequenceNumber.
         * @param  sequenceNumber  String value for sequenceNumber.
         * @return Builder
         */
        public Builder sequenceNumber(String sequenceNumber) {
            this.sequenceNumber = sequenceNumber;
            return this;
        }

        /**
         * Builds a new {@link IndividualResponse} object using the set fields.
         * @return {@link IndividualResponse}
         */
        public IndividualResponse build() {
            return new IndividualResponse(currentAddress, sequenceNumber);
        }
    }
}
