/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for IndvSecPrevSecData type.
 */
public class IndvSecPrevSecData {
    private String appointmentDate;
    private String appointmentIndicator;
    private CommDetailsRegNumber commercialDetail;
    private String latestReturns;
    private String resignationDate;
    private String resignationIndicator;
    private String secretaryshipLength;
    private String shares;

    /**
     * Default constructor.
     */
    public IndvSecPrevSecData() {
    }

    /**
     * Initialization constructor.
     * @param  appointmentDate  String value for appointmentDate.
     * @param  appointmentIndicator  String value for appointmentIndicator.
     * @param  commercialDetail  CommDetailsRegNumber value for commercialDetail.
     * @param  latestReturns  String value for latestReturns.
     * @param  resignationDate  String value for resignationDate.
     * @param  resignationIndicator  String value for resignationIndicator.
     * @param  secretaryshipLength  String value for secretaryshipLength.
     * @param  shares  String value for shares.
     */
    public IndvSecPrevSecData(
            String appointmentDate,
            String appointmentIndicator,
            CommDetailsRegNumber commercialDetail,
            String latestReturns,
            String resignationDate,
            String resignationIndicator,
            String secretaryshipLength,
            String shares) {
        this.appointmentDate = appointmentDate;
        this.appointmentIndicator = appointmentIndicator;
        this.commercialDetail = commercialDetail;
        this.latestReturns = latestReturns;
        this.resignationDate = resignationDate;
        this.resignationIndicator = resignationIndicator;
        this.secretaryshipLength = secretaryshipLength;
        this.shares = shares;
    }

    /**
     * Getter for AppointmentDate.
     * Appointment Date (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("AppointmentDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * Setter for AppointmentDate.
     * Appointment Date (yyyy-mm-dd)
     * @param appointmentDate Value for String
     */
    @JsonSetter("AppointmentDate")
    public void setAppointmentDate(String appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    /**
     * Getter for AppointmentIndicator.
     * Previous secretaryship appointment Indicator - E-exact, P-prior to
     * @return Returns the String
     */
    @JsonGetter("AppointmentIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAppointmentIndicator() {
        return appointmentIndicator;
    }

    /**
     * Setter for AppointmentIndicator.
     * Previous secretaryship appointment Indicator - E-exact, P-prior to
     * @param appointmentIndicator Value for String
     */
    @JsonSetter("AppointmentIndicator")
    public void setAppointmentIndicator(String appointmentIndicator) {
        this.appointmentIndicator = appointmentIndicator;
    }

    /**
     * Getter for CommercialDetail.
     * @return Returns the CommDetailsRegNumber
     */
    @JsonGetter("CommercialDetail")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CommDetailsRegNumber getCommercialDetail() {
        return commercialDetail;
    }

    /**
     * Setter for CommercialDetail.
     * @param commercialDetail Value for CommDetailsRegNumber
     */
    @JsonSetter("CommercialDetail")
    public void setCommercialDetail(CommDetailsRegNumber commercialDetail) {
        this.commercialDetail = commercialDetail;
    }

    /**
     * Getter for LatestReturns.
     * Latest Returns date (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("LatestReturns")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLatestReturns() {
        return latestReturns;
    }

    /**
     * Setter for LatestReturns.
     * Latest Returns date (yyyy-mm-dd)
     * @param latestReturns Value for String
     */
    @JsonSetter("LatestReturns")
    public void setLatestReturns(String latestReturns) {
        this.latestReturns = latestReturns;
    }

    /**
     * Getter for ResignationDate.
     * Resignation Date (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("ResignationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getResignationDate() {
        return resignationDate;
    }

    /**
     * Setter for ResignationDate.
     * Resignation Date (yyyy-mm-dd)
     * @param resignationDate Value for String
     */
    @JsonSetter("ResignationDate")
    public void setResignationDate(String resignationDate) {
        this.resignationDate = resignationDate;
    }

    /**
     * Getter for ResignationIndicator.
     * Previous secretaryship resignation Indicator - E-exact, P-prior to
     * @return Returns the String
     */
    @JsonGetter("ResignationIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getResignationIndicator() {
        return resignationIndicator;
    }

    /**
     * Setter for ResignationIndicator.
     * Previous secretaryship resignation Indicator - E-exact, P-prior to
     * @param resignationIndicator Value for String
     */
    @JsonSetter("ResignationIndicator")
    public void setResignationIndicator(String resignationIndicator) {
        this.resignationIndicator = resignationIndicator;
    }

    /**
     * Getter for SecretaryshipLength.
     * Length of previous secretaryship in months
     * @return Returns the String
     */
    @JsonGetter("SecretaryshipLength")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSecretaryshipLength() {
        return secretaryshipLength;
    }

    /**
     * Setter for SecretaryshipLength.
     * Length of previous secretaryship in months
     * @param secretaryshipLength Value for String
     */
    @JsonSetter("SecretaryshipLength")
    public void setSecretaryshipLength(String secretaryshipLength) {
        this.secretaryshipLength = secretaryshipLength;
    }

    /**
     * Getter for Shares.
     * Shares held by previous Secretary within previous secretaryship
     * @return Returns the String
     */
    @JsonGetter("Shares")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getShares() {
        return shares;
    }

    /**
     * Setter for Shares.
     * Shares held by previous Secretary within previous secretaryship
     * @param shares Value for String
     */
    @JsonSetter("Shares")
    public void setShares(String shares) {
        this.shares = shares;
    }

    /**
     * Converts this IndvSecPrevSecData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IndvSecPrevSecData [" + "appointmentDate=" + appointmentDate
                + ", appointmentIndicator=" + appointmentIndicator + ", commercialDetail="
                + commercialDetail + ", latestReturns=" + latestReturns + ", resignationDate="
                + resignationDate + ", resignationIndicator=" + resignationIndicator
                + ", secretaryshipLength=" + secretaryshipLength + ", shares=" + shares + "]";
    }

    /**
     * Builds a new {@link IndvSecPrevSecData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IndvSecPrevSecData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .appointmentDate(getAppointmentDate())
                .appointmentIndicator(getAppointmentIndicator())
                .commercialDetail(getCommercialDetail())
                .latestReturns(getLatestReturns())
                .resignationDate(getResignationDate())
                .resignationIndicator(getResignationIndicator())
                .secretaryshipLength(getSecretaryshipLength())
                .shares(getShares());
        return builder;
    }

    /**
     * Class to build instances of {@link IndvSecPrevSecData}.
     */
    public static class Builder {
        private String appointmentDate;
        private String appointmentIndicator;
        private CommDetailsRegNumber commercialDetail;
        private String latestReturns;
        private String resignationDate;
        private String resignationIndicator;
        private String secretaryshipLength;
        private String shares;



        /**
         * Setter for appointmentDate.
         * @param  appointmentDate  String value for appointmentDate.
         * @return Builder
         */
        public Builder appointmentDate(String appointmentDate) {
            this.appointmentDate = appointmentDate;
            return this;
        }

        /**
         * Setter for appointmentIndicator.
         * @param  appointmentIndicator  String value for appointmentIndicator.
         * @return Builder
         */
        public Builder appointmentIndicator(String appointmentIndicator) {
            this.appointmentIndicator = appointmentIndicator;
            return this;
        }

        /**
         * Setter for commercialDetail.
         * @param  commercialDetail  CommDetailsRegNumber value for commercialDetail.
         * @return Builder
         */
        public Builder commercialDetail(CommDetailsRegNumber commercialDetail) {
            this.commercialDetail = commercialDetail;
            return this;
        }

        /**
         * Setter for latestReturns.
         * @param  latestReturns  String value for latestReturns.
         * @return Builder
         */
        public Builder latestReturns(String latestReturns) {
            this.latestReturns = latestReturns;
            return this;
        }

        /**
         * Setter for resignationDate.
         * @param  resignationDate  String value for resignationDate.
         * @return Builder
         */
        public Builder resignationDate(String resignationDate) {
            this.resignationDate = resignationDate;
            return this;
        }

        /**
         * Setter for resignationIndicator.
         * @param  resignationIndicator  String value for resignationIndicator.
         * @return Builder
         */
        public Builder resignationIndicator(String resignationIndicator) {
            this.resignationIndicator = resignationIndicator;
            return this;
        }

        /**
         * Setter for secretaryshipLength.
         * @param  secretaryshipLength  String value for secretaryshipLength.
         * @return Builder
         */
        public Builder secretaryshipLength(String secretaryshipLength) {
            this.secretaryshipLength = secretaryshipLength;
            return this;
        }

        /**
         * Setter for shares.
         * @param  shares  String value for shares.
         * @return Builder
         */
        public Builder shares(String shares) {
            this.shares = shares;
            return this;
        }

        /**
         * Builds a new {@link IndvSecPrevSecData} object using the set fields.
         * @return {@link IndvSecPrevSecData}
         */
        public IndvSecPrevSecData build() {
            return new IndvSecPrevSecData(appointmentDate, appointmentIndicator, commercialDetail,
                    latestReturns, resignationDate, resignationIndicator, secretaryshipLength,
                    shares);
        }
    }
}
