/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for InputLocationDetail type.
 */
public class InputLocationDetail {
    private String postTown;
    private String postcode;

    /**
     * Default constructor.
     */
    public InputLocationDetail() {
    }

    /**
     * Initialization constructor.
     * @param  postTown  String value for postTown.
     * @param  postcode  String value for postcode.
     */
    public InputLocationDetail(
            String postTown,
            String postcode) {
        this.postTown = postTown;
        this.postcode = postcode;
    }

    /**
     * Getter for PostTown.
     * @return Returns the String
     */
    @JsonGetter("PostTown")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPostTown() {
        return postTown;
    }

    /**
     * Setter for PostTown.
     * @param postTown Value for String
     */
    @JsonSetter("PostTown")
    public void setPostTown(String postTown) {
        this.postTown = postTown;
    }

    /**
     * Getter for Postcode.
     * @return Returns the String
     */
    @JsonGetter("Postcode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPostcode() {
        return postcode;
    }

    /**
     * Setter for Postcode.
     * @param postcode Value for String
     */
    @JsonSetter("Postcode")
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * Converts this InputLocationDetail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InputLocationDetail [" + "postTown=" + postTown + ", postcode=" + postcode + "]";
    }

    /**
     * Builds a new {@link InputLocationDetail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InputLocationDetail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .postTown(getPostTown())
                .postcode(getPostcode());
        return builder;
    }

    /**
     * Class to build instances of {@link InputLocationDetail}.
     */
    public static class Builder {
        private String postTown;
        private String postcode;



        /**
         * Setter for postTown.
         * @param  postTown  String value for postTown.
         * @return Builder
         */
        public Builder postTown(String postTown) {
            this.postTown = postTown;
            return this;
        }

        /**
         * Setter for postcode.
         * @param  postcode  String value for postcode.
         * @return Builder
         */
        public Builder postcode(String postcode) {
            this.postcode = postcode;
            return this;
        }

        /**
         * Builds a new {@link InputLocationDetail} object using the set fields.
         * @return {@link InputLocationDetail}
         */
        public InputLocationDetail build() {
            return new InputLocationDetail(postTown, postcode);
        }
    }
}
