/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for InstrHolder type.
 */
public class InstrHolder {
    private String name;

    /**
     * Default constructor.
     */
    public InstrHolder() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     */
    public InstrHolder(
            String name) {
        this.name = name;
    }

    /**
     * Getter for Name.
     * Name of Instrument Holder for the appointment of Receivers for the limited company
     * @return Returns the String
     */
    @JsonGetter("Name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of Instrument Holder for the appointment of Receivers for the limited company
     * @param name Value for String
     */
    @JsonSetter("Name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Converts this InstrHolder into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstrHolder [" + "name=" + name + "]";
    }

    /**
     * Builds a new {@link InstrHolder.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstrHolder.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName());
        return builder;
    }

    /**
     * Class to build instances of {@link InstrHolder}.
     */
    public static class Builder {
        private String name;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Builds a new {@link InstrHolder} object using the set fields.
         * @return {@link InstrHolder}
         */
        public InstrHolder build() {
            return new InstrHolder(name);
        }
    }
}
