/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for LimitedCompanyCAISMembersSummary type.
 */
public class LimitedCompanyCAISMembersSummary {
    private String ageSinceLast89;
    private String monthCount;
    private List<LtdMonthlyData> monthlyData;

    /**
     * Default constructor.
     */
    public LimitedCompanyCAISMembersSummary() {
    }

    /**
     * Initialization constructor.
     * @param  ageSinceLast89  String value for ageSinceLast89.
     * @param  monthCount  String value for monthCount.
     * @param  monthlyData  List of LtdMonthlyData value for monthlyData.
     */
    public LimitedCompanyCAISMembersSummary(
            String ageSinceLast89,
            String monthCount,
            List<LtdMonthlyData> monthlyData) {
        this.ageSinceLast89 = ageSinceLast89;
        this.monthCount = monthCount;
        this.monthlyData = monthlyData;
    }

    /**
     * Getter for AgeSinceLast89.
     * Time since last status 8 or 9 (Months)
     * @return Returns the String
     */
    @JsonGetter("AgeSinceLast89")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAgeSinceLast89() {
        return ageSinceLast89;
    }

    /**
     * Setter for AgeSinceLast89.
     * Time since last status 8 or 9 (Months)
     * @param ageSinceLast89 Value for String
     */
    @JsonSetter("AgeSinceLast89")
    public void setAgeSinceLast89(String ageSinceLast89) {
        this.ageSinceLast89 = ageSinceLast89;
    }

    /**
     * Getter for MonthCount.
     * Number of months data (Currently set to 12)
     * @return Returns the String
     */
    @JsonGetter("MonthCount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMonthCount() {
        return monthCount;
    }

    /**
     * Setter for MonthCount.
     * Number of months data (Currently set to 12)
     * @param monthCount Value for String
     */
    @JsonSetter("MonthCount")
    public void setMonthCount(String monthCount) {
        this.monthCount = monthCount;
    }

    /**
     * Getter for MonthlyData.
     * @return Returns the List of LtdMonthlyData
     */
    @JsonGetter("MonthlyData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LtdMonthlyData> getMonthlyData() {
        return monthlyData;
    }

    /**
     * Setter for MonthlyData.
     * @param monthlyData Value for List of LtdMonthlyData
     */
    @JsonSetter("MonthlyData")
    public void setMonthlyData(List<LtdMonthlyData> monthlyData) {
        this.monthlyData = monthlyData;
    }

    /**
     * Converts this LimitedCompanyCAISMembersSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LimitedCompanyCAISMembersSummary [" + "ageSinceLast89=" + ageSinceLast89
                + ", monthCount=" + monthCount + ", monthlyData=" + monthlyData + "]";
    }

    /**
     * Builds a new {@link LimitedCompanyCAISMembersSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LimitedCompanyCAISMembersSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ageSinceLast89(getAgeSinceLast89())
                .monthCount(getMonthCount())
                .monthlyData(getMonthlyData());
        return builder;
    }

    /**
     * Class to build instances of {@link LimitedCompanyCAISMembersSummary}.
     */
    public static class Builder {
        private String ageSinceLast89;
        private String monthCount;
        private List<LtdMonthlyData> monthlyData;



        /**
         * Setter for ageSinceLast89.
         * @param  ageSinceLast89  String value for ageSinceLast89.
         * @return Builder
         */
        public Builder ageSinceLast89(String ageSinceLast89) {
            this.ageSinceLast89 = ageSinceLast89;
            return this;
        }

        /**
         * Setter for monthCount.
         * @param  monthCount  String value for monthCount.
         * @return Builder
         */
        public Builder monthCount(String monthCount) {
            this.monthCount = monthCount;
            return this;
        }

        /**
         * Setter for monthlyData.
         * @param  monthlyData  List of LtdMonthlyData value for monthlyData.
         * @return Builder
         */
        public Builder monthlyData(List<LtdMonthlyData> monthlyData) {
            this.monthlyData = monthlyData;
            return this;
        }

        /**
         * Builds a new {@link LimitedCompanyCAISMembersSummary} object using the set fields.
         * @return {@link LimitedCompanyCAISMembersSummary}
         */
        public LimitedCompanyCAISMembersSummary build() {
            return new LimitedCompanyCAISMembersSummary(ageSinceLast89, monthCount, monthlyData);
        }
    }
}
