/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for LimitedCompanyDelphiCAIS type.
 */
public class LimitedCompanyDelphiCAIS {
    private String ageMostRecent;
    private String avgBalanceOwnAccounts;
    private String balanceActiveAccounts;
    private String numActiveAccounts;
    private String numDefaults;
    private String numOwnAccounts;
    private String numSettled;
    private String totalBalanceOwnAccounts;
    private String valueDefaults;
    private String worstStatusActive;
    private String worstStatusOld;

    /**
     * Default constructor.
     */
    public LimitedCompanyDelphiCAIS() {
    }

    /**
     * Initialization constructor.
     * @param  ageMostRecent  String value for ageMostRecent.
     * @param  avgBalanceOwnAccounts  String value for avgBalanceOwnAccounts.
     * @param  balanceActiveAccounts  String value for balanceActiveAccounts.
     * @param  numActiveAccounts  String value for numActiveAccounts.
     * @param  numDefaults  String value for numDefaults.
     * @param  numOwnAccounts  String value for numOwnAccounts.
     * @param  numSettled  String value for numSettled.
     * @param  totalBalanceOwnAccounts  String value for totalBalanceOwnAccounts.
     * @param  valueDefaults  String value for valueDefaults.
     * @param  worstStatusActive  String value for worstStatusActive.
     * @param  worstStatusOld  String value for worstStatusOld.
     */
    public LimitedCompanyDelphiCAIS(
            String ageMostRecent,
            String avgBalanceOwnAccounts,
            String balanceActiveAccounts,
            String numActiveAccounts,
            String numDefaults,
            String numOwnAccounts,
            String numSettled,
            String totalBalanceOwnAccounts,
            String valueDefaults,
            String worstStatusActive,
            String worstStatusOld) {
        this.ageMostRecent = ageMostRecent;
        this.avgBalanceOwnAccounts = avgBalanceOwnAccounts;
        this.balanceActiveAccounts = balanceActiveAccounts;
        this.numActiveAccounts = numActiveAccounts;
        this.numDefaults = numDefaults;
        this.numOwnAccounts = numOwnAccounts;
        this.numSettled = numSettled;
        this.totalBalanceOwnAccounts = totalBalanceOwnAccounts;
        this.valueDefaults = valueDefaults;
        this.worstStatusActive = worstStatusActive;
        this.worstStatusOld = worstStatusOld;
    }

    /**
     * Getter for AgeMostRecent.
     * Age of most recent CAIS 8/9 (Months)
     * @return Returns the String
     */
    @JsonGetter("AgeMostRecent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAgeMostRecent() {
        return ageMostRecent;
    }

    /**
     * Setter for AgeMostRecent.
     * Age of most recent CAIS 8/9 (Months)
     * @param ageMostRecent Value for String
     */
    @JsonSetter("AgeMostRecent")
    public void setAgeMostRecent(String ageMostRecent) {
        this.ageMostRecent = ageMostRecent;
    }

    /**
     * Getter for AvgBalanceOwnAccounts.
     * Average balance of own company instalment CAIS accounts
     * @return Returns the String
     */
    @JsonGetter("AvgBalanceOwnAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAvgBalanceOwnAccounts() {
        return avgBalanceOwnAccounts;
    }

    /**
     * Setter for AvgBalanceOwnAccounts.
     * Average balance of own company instalment CAIS accounts
     * @param avgBalanceOwnAccounts Value for String
     */
    @JsonSetter("AvgBalanceOwnAccounts")
    public void setAvgBalanceOwnAccounts(String avgBalanceOwnAccounts) {
        this.avgBalanceOwnAccounts = avgBalanceOwnAccounts;
    }

    /**
     * Getter for BalanceActiveAccounts.
     * Total balance outstanding on active accounts
     * @return Returns the String
     */
    @JsonGetter("BalanceActiveAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBalanceActiveAccounts() {
        return balanceActiveAccounts;
    }

    /**
     * Setter for BalanceActiveAccounts.
     * Total balance outstanding on active accounts
     * @param balanceActiveAccounts Value for String
     */
    @JsonSetter("BalanceActiveAccounts")
    public void setBalanceActiveAccounts(String balanceActiveAccounts) {
        this.balanceActiveAccounts = balanceActiveAccounts;
    }

    /**
     * Getter for NumActiveAccounts.
     * Total number active accounts
     * @return Returns the String
     */
    @JsonGetter("NumActiveAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNumActiveAccounts() {
        return numActiveAccounts;
    }

    /**
     * Setter for NumActiveAccounts.
     * Total number active accounts
     * @param numActiveAccounts Value for String
     */
    @JsonSetter("NumActiveAccounts")
    public void setNumActiveAccounts(String numActiveAccounts) {
        this.numActiveAccounts = numActiveAccounts;
    }

    /**
     * Getter for NumDefaults.
     * Number of CAIS 8/9s
     * @return Returns the String
     */
    @JsonGetter("NumDefaults")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNumDefaults() {
        return numDefaults;
    }

    /**
     * Setter for NumDefaults.
     * Number of CAIS 8/9s
     * @param numDefaults Value for String
     */
    @JsonSetter("NumDefaults")
    public void setNumDefaults(String numDefaults) {
        this.numDefaults = numDefaults;
    }

    /**
     * Getter for NumOwnAccounts.
     * Number of own company instalment CAIS accounts
     * @return Returns the String
     */
    @JsonGetter("NumOwnAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNumOwnAccounts() {
        return numOwnAccounts;
    }

    /**
     * Setter for NumOwnAccounts.
     * Number of own company instalment CAIS accounts
     * @param numOwnAccounts Value for String
     */
    @JsonSetter("NumOwnAccounts")
    public void setNumOwnAccounts(String numOwnAccounts) {
        this.numOwnAccounts = numOwnAccounts;
    }

    /**
     * Getter for NumSettled.
     * Number of settled CAIS 0s
     * @return Returns the String
     */
    @JsonGetter("NumSettled")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNumSettled() {
        return numSettled;
    }

    /**
     * Setter for NumSettled.
     * Number of settled CAIS 0s
     * @param numSettled Value for String
     */
    @JsonSetter("NumSettled")
    public void setNumSettled(String numSettled) {
        this.numSettled = numSettled;
    }

    /**
     * Getter for TotalBalanceOwnAccounts.
     * Total value of own company instalment CAIS accounts
     * @return Returns the String
     */
    @JsonGetter("TotalBalanceOwnAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTotalBalanceOwnAccounts() {
        return totalBalanceOwnAccounts;
    }

    /**
     * Setter for TotalBalanceOwnAccounts.
     * Total value of own company instalment CAIS accounts
     * @param totalBalanceOwnAccounts Value for String
     */
    @JsonSetter("TotalBalanceOwnAccounts")
    public void setTotalBalanceOwnAccounts(String totalBalanceOwnAccounts) {
        this.totalBalanceOwnAccounts = totalBalanceOwnAccounts;
    }

    /**
     * Getter for ValueDefaults.
     * Total value CAIS 8/9s
     * @return Returns the String
     */
    @JsonGetter("ValueDefaults")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getValueDefaults() {
        return valueDefaults;
    }

    /**
     * Setter for ValueDefaults.
     * Total value CAIS 8/9s
     * @param valueDefaults Value for String
     */
    @JsonSetter("ValueDefaults")
    public void setValueDefaults(String valueDefaults) {
        this.valueDefaults = valueDefaults;
    }

    /**
     * Getter for WorstStatusActive.
     * Worst current status on active accounts
     * @return Returns the String
     */
    @JsonGetter("WorstStatusActive")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWorstStatusActive() {
        return worstStatusActive;
    }

    /**
     * Setter for WorstStatusActive.
     * Worst current status on active accounts
     * @param worstStatusActive Value for String
     */
    @JsonSetter("WorstStatusActive")
    public void setWorstStatusActive(String worstStatusActive) {
        this.worstStatusActive = worstStatusActive;
    }

    /**
     * Getter for WorstStatusOld.
     * Worst status in last 3 months on accounts opened over 12 months ago
     * @return Returns the String
     */
    @JsonGetter("WorstStatusOld")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWorstStatusOld() {
        return worstStatusOld;
    }

    /**
     * Setter for WorstStatusOld.
     * Worst status in last 3 months on accounts opened over 12 months ago
     * @param worstStatusOld Value for String
     */
    @JsonSetter("WorstStatusOld")
    public void setWorstStatusOld(String worstStatusOld) {
        this.worstStatusOld = worstStatusOld;
    }

    /**
     * Converts this LimitedCompanyDelphiCAIS into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LimitedCompanyDelphiCAIS [" + "ageMostRecent=" + ageMostRecent
                + ", avgBalanceOwnAccounts=" + avgBalanceOwnAccounts + ", balanceActiveAccounts="
                + balanceActiveAccounts + ", numActiveAccounts=" + numActiveAccounts
                + ", numDefaults=" + numDefaults + ", numOwnAccounts=" + numOwnAccounts
                + ", numSettled=" + numSettled + ", totalBalanceOwnAccounts="
                + totalBalanceOwnAccounts + ", valueDefaults=" + valueDefaults
                + ", worstStatusActive=" + worstStatusActive + ", worstStatusOld=" + worstStatusOld
                + "]";
    }

    /**
     * Builds a new {@link LimitedCompanyDelphiCAIS.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LimitedCompanyDelphiCAIS.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ageMostRecent(getAgeMostRecent())
                .avgBalanceOwnAccounts(getAvgBalanceOwnAccounts())
                .balanceActiveAccounts(getBalanceActiveAccounts())
                .numActiveAccounts(getNumActiveAccounts())
                .numDefaults(getNumDefaults())
                .numOwnAccounts(getNumOwnAccounts())
                .numSettled(getNumSettled())
                .totalBalanceOwnAccounts(getTotalBalanceOwnAccounts())
                .valueDefaults(getValueDefaults())
                .worstStatusActive(getWorstStatusActive())
                .worstStatusOld(getWorstStatusOld());
        return builder;
    }

    /**
     * Class to build instances of {@link LimitedCompanyDelphiCAIS}.
     */
    public static class Builder {
        private String ageMostRecent;
        private String avgBalanceOwnAccounts;
        private String balanceActiveAccounts;
        private String numActiveAccounts;
        private String numDefaults;
        private String numOwnAccounts;
        private String numSettled;
        private String totalBalanceOwnAccounts;
        private String valueDefaults;
        private String worstStatusActive;
        private String worstStatusOld;



        /**
         * Setter for ageMostRecent.
         * @param  ageMostRecent  String value for ageMostRecent.
         * @return Builder
         */
        public Builder ageMostRecent(String ageMostRecent) {
            this.ageMostRecent = ageMostRecent;
            return this;
        }

        /**
         * Setter for avgBalanceOwnAccounts.
         * @param  avgBalanceOwnAccounts  String value for avgBalanceOwnAccounts.
         * @return Builder
         */
        public Builder avgBalanceOwnAccounts(String avgBalanceOwnAccounts) {
            this.avgBalanceOwnAccounts = avgBalanceOwnAccounts;
            return this;
        }

        /**
         * Setter for balanceActiveAccounts.
         * @param  balanceActiveAccounts  String value for balanceActiveAccounts.
         * @return Builder
         */
        public Builder balanceActiveAccounts(String balanceActiveAccounts) {
            this.balanceActiveAccounts = balanceActiveAccounts;
            return this;
        }

        /**
         * Setter for numActiveAccounts.
         * @param  numActiveAccounts  String value for numActiveAccounts.
         * @return Builder
         */
        public Builder numActiveAccounts(String numActiveAccounts) {
            this.numActiveAccounts = numActiveAccounts;
            return this;
        }

        /**
         * Setter for numDefaults.
         * @param  numDefaults  String value for numDefaults.
         * @return Builder
         */
        public Builder numDefaults(String numDefaults) {
            this.numDefaults = numDefaults;
            return this;
        }

        /**
         * Setter for numOwnAccounts.
         * @param  numOwnAccounts  String value for numOwnAccounts.
         * @return Builder
         */
        public Builder numOwnAccounts(String numOwnAccounts) {
            this.numOwnAccounts = numOwnAccounts;
            return this;
        }

        /**
         * Setter for numSettled.
         * @param  numSettled  String value for numSettled.
         * @return Builder
         */
        public Builder numSettled(String numSettled) {
            this.numSettled = numSettled;
            return this;
        }

        /**
         * Setter for totalBalanceOwnAccounts.
         * @param  totalBalanceOwnAccounts  String value for totalBalanceOwnAccounts.
         * @return Builder
         */
        public Builder totalBalanceOwnAccounts(String totalBalanceOwnAccounts) {
            this.totalBalanceOwnAccounts = totalBalanceOwnAccounts;
            return this;
        }

        /**
         * Setter for valueDefaults.
         * @param  valueDefaults  String value for valueDefaults.
         * @return Builder
         */
        public Builder valueDefaults(String valueDefaults) {
            this.valueDefaults = valueDefaults;
            return this;
        }

        /**
         * Setter for worstStatusActive.
         * @param  worstStatusActive  String value for worstStatusActive.
         * @return Builder
         */
        public Builder worstStatusActive(String worstStatusActive) {
            this.worstStatusActive = worstStatusActive;
            return this;
        }

        /**
         * Setter for worstStatusOld.
         * @param  worstStatusOld  String value for worstStatusOld.
         * @return Builder
         */
        public Builder worstStatusOld(String worstStatusOld) {
            this.worstStatusOld = worstStatusOld;
            return this;
        }

        /**
         * Builds a new {@link LimitedCompanyDelphiCAIS} object using the set fields.
         * @return {@link LimitedCompanyDelphiCAIS}
         */
        public LimitedCompanyDelphiCAIS build() {
            return new LimitedCompanyDelphiCAIS(ageMostRecent, avgBalanceOwnAccounts,
                    balanceActiveAccounts, numActiveAccounts, numDefaults, numOwnAccounts,
                    numSettled, totalBalanceOwnAccounts, valueDefaults, worstStatusActive,
                    worstStatusOld);
        }
    }
}
