/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for Location1 type.
 */
public class Location1 {
    private String flat;
    private String houseName;
    private String houseNumber;
    private String street;
    private String district;
    private String town;
    private String county;
    private String postcode;

    /**
     * Default constructor.
     */
    public Location1() {
    }

    /**
     * Initialization constructor.
     * @param  flat  String value for flat.
     * @param  houseName  String value for houseName.
     * @param  houseNumber  String value for houseNumber.
     * @param  street  String value for street.
     * @param  district  String value for district.
     * @param  town  String value for town.
     * @param  county  String value for county.
     * @param  postcode  String value for postcode.
     */
    public Location1(
            String flat,
            String houseName,
            String houseNumber,
            String street,
            String district,
            String town,
            String county,
            String postcode) {
        this.flat = flat;
        this.houseName = houseName;
        this.houseNumber = houseNumber;
        this.street = street;
        this.district = district;
        this.town = town;
        this.county = county;
        this.postcode = postcode;
    }

    /**
     * Getter for Flat.
     * Current Proprietors address flat name Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("Flat")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFlat() {
        return flat;
    }

    /**
     * Setter for Flat.
     * Current Proprietors address flat name Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param flat Value for String
     */
    @JsonSetter("Flat")
    public void setFlat(String flat) {
        this.flat = flat;
    }

    /**
     * Getter for HouseName.
     * Current Proprietors address house name Only available to Business Person User Group within
     * the CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("HouseName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHouseName() {
        return houseName;
    }

    /**
     * Setter for HouseName.
     * Current Proprietors address house name Only available to Business Person User Group within
     * the CAIS data sharing program.
     * @param houseName Value for String
     */
    @JsonSetter("HouseName")
    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    /**
     * Getter for HouseNumber.
     * Current Proprietors address house number Only available to Business Person User Group within
     * the CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("HouseNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * Setter for HouseNumber.
     * Current Proprietors address house number Only available to Business Person User Group within
     * the CAIS data sharing program.
     * @param houseNumber Value for String
     */
    @JsonSetter("HouseNumber")
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * Getter for Street.
     * Current Proprietors address line 1 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("Street")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStreet() {
        return street;
    }

    /**
     * Setter for Street.
     * Current Proprietors address line 1 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param street Value for String
     */
    @JsonSetter("Street")
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Getter for District.
     * Current Proprietors address line 2 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("District")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDistrict() {
        return district;
    }

    /**
     * Setter for District.
     * Current Proprietors address line 2 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param district Value for String
     */
    @JsonSetter("District")
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * Getter for Town.
     * Current Proprietors address line 3 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("Town")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTown() {
        return town;
    }

    /**
     * Setter for Town.
     * Current Proprietors address line 3 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param town Value for String
     */
    @JsonSetter("Town")
    public void setTown(String town) {
        this.town = town;
    }

    /**
     * Getter for County.
     * Current Proprietors address line 4 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("County")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCounty() {
        return county;
    }

    /**
     * Setter for County.
     * Current Proprietors address line 4 Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param county Value for String
     */
    @JsonSetter("County")
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * Getter for Postcode.
     * Current Proprietors address postcode Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @return Returns the String
     */
    @JsonGetter("Postcode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPostcode() {
        return postcode;
    }

    /**
     * Setter for Postcode.
     * Current Proprietors address postcode Only available to Business Person User Group within the
     * CAIS data sharing program.
     * @param postcode Value for String
     */
    @JsonSetter("Postcode")
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * Converts this Location1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Location1 [" + "flat=" + flat + ", houseName=" + houseName + ", houseNumber="
                + houseNumber + ", street=" + street + ", district=" + district + ", town=" + town
                + ", county=" + county + ", postcode=" + postcode + "]";
    }

    /**
     * Builds a new {@link Location1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Location1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .flat(getFlat())
                .houseName(getHouseName())
                .houseNumber(getHouseNumber())
                .street(getStreet())
                .district(getDistrict())
                .town(getTown())
                .county(getCounty())
                .postcode(getPostcode());
        return builder;
    }

    /**
     * Class to build instances of {@link Location1}.
     */
    public static class Builder {
        private String flat;
        private String houseName;
        private String houseNumber;
        private String street;
        private String district;
        private String town;
        private String county;
        private String postcode;



        /**
         * Setter for flat.
         * @param  flat  String value for flat.
         * @return Builder
         */
        public Builder flat(String flat) {
            this.flat = flat;
            return this;
        }

        /**
         * Setter for houseName.
         * @param  houseName  String value for houseName.
         * @return Builder
         */
        public Builder houseName(String houseName) {
            this.houseName = houseName;
            return this;
        }

        /**
         * Setter for houseNumber.
         * @param  houseNumber  String value for houseNumber.
         * @return Builder
         */
        public Builder houseNumber(String houseNumber) {
            this.houseNumber = houseNumber;
            return this;
        }

        /**
         * Setter for street.
         * @param  street  String value for street.
         * @return Builder
         */
        public Builder street(String street) {
            this.street = street;
            return this;
        }

        /**
         * Setter for district.
         * @param  district  String value for district.
         * @return Builder
         */
        public Builder district(String district) {
            this.district = district;
            return this;
        }

        /**
         * Setter for town.
         * @param  town  String value for town.
         * @return Builder
         */
        public Builder town(String town) {
            this.town = town;
            return this;
        }

        /**
         * Setter for county.
         * @param  county  String value for county.
         * @return Builder
         */
        public Builder county(String county) {
            this.county = county;
            return this;
        }

        /**
         * Setter for postcode.
         * @param  postcode  String value for postcode.
         * @return Builder
         */
        public Builder postcode(String postcode) {
            this.postcode = postcode;
            return this;
        }

        /**
         * Builds a new {@link Location1} object using the set fields.
         * @return {@link Location1}
         */
        public Location1 build() {
            return new Location1(flat, houseName, houseNumber, street, district, town, county,
                    postcode);
        }
    }
}
