/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for LtdMonthlyData type.
 */
public class LtdMonthlyData {
    private int currentBalance;
    private int defaultBalance;
    private String monthMm;
    private String monthYyyy;
    private int numActiveAccounts;
    private int status0;
    private int status1;
    private int status2;
    private int status3;
    private int status4;
    private int status5;
    private int status6;
    private int status89;
    private int statusU;

    /**
     * Default constructor.
     */
    public LtdMonthlyData() {
    }

    /**
     * Initialization constructor.
     * @param  currentBalance  int value for currentBalance.
     * @param  defaultBalance  int value for defaultBalance.
     * @param  numActiveAccounts  int value for numActiveAccounts.
     * @param  status0  int value for status0.
     * @param  status1  int value for status1.
     * @param  status2  int value for status2.
     * @param  status3  int value for status3.
     * @param  status4  int value for status4.
     * @param  status5  int value for status5.
     * @param  status6  int value for status6.
     * @param  status89  int value for status89.
     * @param  statusU  int value for statusU.
     * @param  monthMm  String value for monthMm.
     * @param  monthYyyy  String value for monthYyyy.
     */
    public LtdMonthlyData(
            int currentBalance,
            int defaultBalance,
            int numActiveAccounts,
            int status0,
            int status1,
            int status2,
            int status3,
            int status4,
            int status5,
            int status6,
            int status89,
            int statusU,
            String monthMm,
            String monthYyyy) {
        this.currentBalance = currentBalance;
        this.defaultBalance = defaultBalance;
        this.monthMm = monthMm;
        this.monthYyyy = monthYyyy;
        this.numActiveAccounts = numActiveAccounts;
        this.status0 = status0;
        this.status1 = status1;
        this.status2 = status2;
        this.status3 = status3;
        this.status4 = status4;
        this.status5 = status5;
        this.status6 = status6;
        this.status89 = status89;
        this.statusU = statusU;
    }

    /**
     * Getter for CurrentBalance.
     * Current balance
     * @return Returns the int
     */
    @JsonGetter("CurrentBalance")
    public int getCurrentBalance() {
        return currentBalance;
    }

    /**
     * Setter for CurrentBalance.
     * Current balance
     * @param currentBalance Value for int
     */
    @JsonSetter("CurrentBalance")
    public void setCurrentBalance(int currentBalance) {
        this.currentBalance = currentBalance;
    }

    /**
     * Getter for DefaultBalance.
     * Default balance
     * @return Returns the int
     */
    @JsonGetter("DefaultBalance")
    public int getDefaultBalance() {
        return defaultBalance;
    }

    /**
     * Setter for DefaultBalance.
     * Default balance
     * @param defaultBalance Value for int
     */
    @JsonSetter("DefaultBalance")
    public void setDefaultBalance(int defaultBalance) {
        this.defaultBalance = defaultBalance;
    }

    /**
     * Getter for MonthMm.
     * Month - MM
     * @return Returns the String
     */
    @JsonGetter("Month-Mm")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMonthMm() {
        return monthMm;
    }

    /**
     * Setter for MonthMm.
     * Month - MM
     * @param monthMm Value for String
     */
    @JsonSetter("Month-Mm")
    public void setMonthMm(String monthMm) {
        this.monthMm = monthMm;
    }

    /**
     * Getter for MonthYyyy.
     * Month - YYYY
     * @return Returns the String
     */
    @JsonGetter("Month-Yyyy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMonthYyyy() {
        return monthYyyy;
    }

    /**
     * Setter for MonthYyyy.
     * Month - YYYY
     * @param monthYyyy Value for String
     */
    @JsonSetter("Month-Yyyy")
    public void setMonthYyyy(String monthYyyy) {
        this.monthYyyy = monthYyyy;
    }

    /**
     * Getter for NumActiveAccounts.
     * Number of active accounts
     * @return Returns the int
     */
    @JsonGetter("NumActiveAccounts")
    public int getNumActiveAccounts() {
        return numActiveAccounts;
    }

    /**
     * Setter for NumActiveAccounts.
     * Number of active accounts
     * @param numActiveAccounts Value for int
     */
    @JsonSetter("NumActiveAccounts")
    public void setNumActiveAccounts(int numActiveAccounts) {
        this.numActiveAccounts = numActiveAccounts;
    }

    /**
     * Getter for Status0.
     * Status 0
     * @return Returns the int
     */
    @JsonGetter("Status0")
    public int getStatus0() {
        return status0;
    }

    /**
     * Setter for Status0.
     * Status 0
     * @param status0 Value for int
     */
    @JsonSetter("Status0")
    public void setStatus0(int status0) {
        this.status0 = status0;
    }

    /**
     * Getter for Status1.
     * Status 1
     * @return Returns the int
     */
    @JsonGetter("Status1")
    public int getStatus1() {
        return status1;
    }

    /**
     * Setter for Status1.
     * Status 1
     * @param status1 Value for int
     */
    @JsonSetter("Status1")
    public void setStatus1(int status1) {
        this.status1 = status1;
    }

    /**
     * Getter for Status2.
     * Status 2
     * @return Returns the int
     */
    @JsonGetter("Status2")
    public int getStatus2() {
        return status2;
    }

    /**
     * Setter for Status2.
     * Status 2
     * @param status2 Value for int
     */
    @JsonSetter("Status2")
    public void setStatus2(int status2) {
        this.status2 = status2;
    }

    /**
     * Getter for Status3.
     * Status 3
     * @return Returns the int
     */
    @JsonGetter("Status3")
    public int getStatus3() {
        return status3;
    }

    /**
     * Setter for Status3.
     * Status 3
     * @param status3 Value for int
     */
    @JsonSetter("Status3")
    public void setStatus3(int status3) {
        this.status3 = status3;
    }

    /**
     * Getter for Status4.
     * Status 4
     * @return Returns the int
     */
    @JsonGetter("Status4")
    public int getStatus4() {
        return status4;
    }

    /**
     * Setter for Status4.
     * Status 4
     * @param status4 Value for int
     */
    @JsonSetter("Status4")
    public void setStatus4(int status4) {
        this.status4 = status4;
    }

    /**
     * Getter for Status5.
     * Status 5
     * @return Returns the int
     */
    @JsonGetter("Status5")
    public int getStatus5() {
        return status5;
    }

    /**
     * Setter for Status5.
     * Status 5
     * @param status5 Value for int
     */
    @JsonSetter("Status5")
    public void setStatus5(int status5) {
        this.status5 = status5;
    }

    /**
     * Getter for Status6.
     * Status 6
     * @return Returns the int
     */
    @JsonGetter("Status6")
    public int getStatus6() {
        return status6;
    }

    /**
     * Setter for Status6.
     * Status 6
     * @param status6 Value for int
     */
    @JsonSetter("Status6")
    public void setStatus6(int status6) {
        this.status6 = status6;
    }

    /**
     * Getter for Status89.
     * Status 8 9
     * @return Returns the int
     */
    @JsonGetter("Status89")
    public int getStatus89() {
        return status89;
    }

    /**
     * Setter for Status89.
     * Status 8 9
     * @param status89 Value for int
     */
    @JsonSetter("Status89")
    public void setStatus89(int status89) {
        this.status89 = status89;
    }

    /**
     * Getter for StatusU.
     * Status U
     * @return Returns the int
     */
    @JsonGetter("StatusU")
    public int getStatusU() {
        return statusU;
    }

    /**
     * Setter for StatusU.
     * Status U
     * @param statusU Value for int
     */
    @JsonSetter("StatusU")
    public void setStatusU(int statusU) {
        this.statusU = statusU;
    }

    /**
     * Converts this LtdMonthlyData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LtdMonthlyData [" + "currentBalance=" + currentBalance + ", defaultBalance="
                + defaultBalance + ", numActiveAccounts=" + numActiveAccounts + ", status0="
                + status0 + ", status1=" + status1 + ", status2=" + status2 + ", status3=" + status3
                + ", status4=" + status4 + ", status5=" + status5 + ", status6=" + status6
                + ", status89=" + status89 + ", statusU=" + statusU + ", monthMm=" + monthMm
                + ", monthYyyy=" + monthYyyy + "]";
    }

    /**
     * Builds a new {@link LtdMonthlyData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LtdMonthlyData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(currentBalance, defaultBalance, numActiveAccounts, status0,
                status1, status2, status3, status4, status5, status6, status89, statusU)
                .monthMm(getMonthMm())
                .monthYyyy(getMonthYyyy());
        return builder;
    }

    /**
     * Class to build instances of {@link LtdMonthlyData}.
     */
    public static class Builder {
        private int currentBalance;
        private int defaultBalance;
        private int numActiveAccounts;
        private int status0;
        private int status1;
        private int status2;
        private int status3;
        private int status4;
        private int status5;
        private int status6;
        private int status89;
        private int statusU;
        private String monthMm;
        private String monthYyyy;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  currentBalance  int value for currentBalance.
         * @param  defaultBalance  int value for defaultBalance.
         * @param  numActiveAccounts  int value for numActiveAccounts.
         * @param  status0  int value for status0.
         * @param  status1  int value for status1.
         * @param  status2  int value for status2.
         * @param  status3  int value for status3.
         * @param  status4  int value for status4.
         * @param  status5  int value for status5.
         * @param  status6  int value for status6.
         * @param  status89  int value for status89.
         * @param  statusU  int value for statusU.
         */
        public Builder(int currentBalance, int defaultBalance, int numActiveAccounts, int status0,
                int status1, int status2, int status3, int status4, int status5, int status6,
                int status89, int statusU) {
            this.currentBalance = currentBalance;
            this.defaultBalance = defaultBalance;
            this.numActiveAccounts = numActiveAccounts;
            this.status0 = status0;
            this.status1 = status1;
            this.status2 = status2;
            this.status3 = status3;
            this.status4 = status4;
            this.status5 = status5;
            this.status6 = status6;
            this.status89 = status89;
            this.statusU = statusU;
        }

        /**
         * Setter for currentBalance.
         * @param  currentBalance  int value for currentBalance.
         * @return Builder
         */
        public Builder currentBalance(int currentBalance) {
            this.currentBalance = currentBalance;
            return this;
        }

        /**
         * Setter for defaultBalance.
         * @param  defaultBalance  int value for defaultBalance.
         * @return Builder
         */
        public Builder defaultBalance(int defaultBalance) {
            this.defaultBalance = defaultBalance;
            return this;
        }

        /**
         * Setter for numActiveAccounts.
         * @param  numActiveAccounts  int value for numActiveAccounts.
         * @return Builder
         */
        public Builder numActiveAccounts(int numActiveAccounts) {
            this.numActiveAccounts = numActiveAccounts;
            return this;
        }

        /**
         * Setter for status0.
         * @param  status0  int value for status0.
         * @return Builder
         */
        public Builder status0(int status0) {
            this.status0 = status0;
            return this;
        }

        /**
         * Setter for status1.
         * @param  status1  int value for status1.
         * @return Builder
         */
        public Builder status1(int status1) {
            this.status1 = status1;
            return this;
        }

        /**
         * Setter for status2.
         * @param  status2  int value for status2.
         * @return Builder
         */
        public Builder status2(int status2) {
            this.status2 = status2;
            return this;
        }

        /**
         * Setter for status3.
         * @param  status3  int value for status3.
         * @return Builder
         */
        public Builder status3(int status3) {
            this.status3 = status3;
            return this;
        }

        /**
         * Setter for status4.
         * @param  status4  int value for status4.
         * @return Builder
         */
        public Builder status4(int status4) {
            this.status4 = status4;
            return this;
        }

        /**
         * Setter for status5.
         * @param  status5  int value for status5.
         * @return Builder
         */
        public Builder status5(int status5) {
            this.status5 = status5;
            return this;
        }

        /**
         * Setter for status6.
         * @param  status6  int value for status6.
         * @return Builder
         */
        public Builder status6(int status6) {
            this.status6 = status6;
            return this;
        }

        /**
         * Setter for status89.
         * @param  status89  int value for status89.
         * @return Builder
         */
        public Builder status89(int status89) {
            this.status89 = status89;
            return this;
        }

        /**
         * Setter for statusU.
         * @param  statusU  int value for statusU.
         * @return Builder
         */
        public Builder statusU(int statusU) {
            this.statusU = statusU;
            return this;
        }

        /**
         * Setter for monthMm.
         * @param  monthMm  String value for monthMm.
         * @return Builder
         */
        public Builder monthMm(String monthMm) {
            this.monthMm = monthMm;
            return this;
        }

        /**
         * Setter for monthYyyy.
         * @param  monthYyyy  String value for monthYyyy.
         * @return Builder
         */
        public Builder monthYyyy(String monthYyyy) {
            this.monthYyyy = monthYyyy;
            return this;
        }

        /**
         * Builds a new {@link LtdMonthlyData} object using the set fields.
         * @return {@link LtdMonthlyData}
         */
        public LtdMonthlyData build() {
            return new LtdMonthlyData(currentBalance, defaultBalance, numActiveAccounts, status0,
                    status1, status2, status3, status4, status5, status6, status89, statusU,
                    monthMm, monthYyyy);
        }
    }
}
