/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for NOCDetail type.
 */
public class NOCDetail {
    private String reference;
    private String text;

    /**
     * Default constructor.
     */
    public NOCDetail() {
    }

    /**
     * Initialization constructor.
     * @param  reference  String value for reference.
     * @param  text  String value for text.
     */
    public NOCDetail(
            String reference,
            String text) {
        this.reference = reference;
        this.text = text;
    }

    /**
     * Getter for Reference.
     * Notice of Correction Reference Number
     * @return Returns the String
     */
    @JsonGetter("Reference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReference() {
        return reference;
    }

    /**
     * Setter for Reference.
     * Notice of Correction Reference Number
     * @param reference Value for String
     */
    @JsonSetter("Reference")
    public void setReference(String reference) {
        this.reference = reference;
    }

    /**
     * Getter for Text.
     * Notice of Correction Text
     * @return Returns the String
     */
    @JsonGetter("Text")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * Notice of Correction Text
     * @param text Value for String
     */
    @JsonSetter("Text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Converts this NOCDetail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NOCDetail [" + "reference=" + reference + ", text=" + text + "]";
    }

    /**
     * Builds a new {@link NOCDetail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NOCDetail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .reference(getReference())
                .text(getText());
        return builder;
    }

    /**
     * Class to build instances of {@link NOCDetail}.
     */
    public static class Builder {
        private String reference;
        private String text;



        /**
         * Setter for reference.
         * @param  reference  String value for reference.
         * @return Builder
         */
        public Builder reference(String reference) {
            this.reference = reference;
            return this;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Builds a new {@link NOCDetail} object using the set fields.
         * @return {@link NOCDetail}
         */
        public NOCDetail build() {
            return new NOCDetail(reference, text);
        }
    }
}
