/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for OutputNameDetail type.
 */
public class OutputNameDetail {
    private String forename;
    private String middleNames;
    private String prefix;
    private String suffix;
    private String surname;

    /**
     * Default constructor.
     */
    public OutputNameDetail() {
    }

    /**
     * Initialization constructor.
     * @param  forename  String value for forename.
     * @param  middleNames  String value for middleNames.
     * @param  prefix  String value for prefix.
     * @param  suffix  String value for suffix.
     * @param  surname  String value for surname.
     */
    public OutputNameDetail(
            String forename,
            String middleNames,
            String prefix,
            String suffix,
            String surname) {
        this.forename = forename;
        this.middleNames = middleNames;
        this.prefix = prefix;
        this.suffix = suffix;
        this.surname = surname;
    }

    /**
     * Getter for Forename.
     * Forename
     * @return Returns the String
     */
    @JsonGetter("Forename")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getForename() {
        return forename;
    }

    /**
     * Setter for Forename.
     * Forename
     * @param forename Value for String
     */
    @JsonSetter("Forename")
    public void setForename(String forename) {
        this.forename = forename;
    }

    /**
     * Getter for MiddleNames.
     * Middle names
     * @return Returns the String
     */
    @JsonGetter("MiddleNames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMiddleNames() {
        return middleNames;
    }

    /**
     * Setter for MiddleNames.
     * Middle names
     * @param middleNames Value for String
     */
    @JsonSetter("MiddleNames")
    public void setMiddleNames(String middleNames) {
        this.middleNames = middleNames;
    }

    /**
     * Getter for Prefix.
     * Name prefix
     * @return Returns the String
     */
    @JsonGetter("Prefix")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrefix() {
        return prefix;
    }

    /**
     * Setter for Prefix.
     * Name prefix
     * @param prefix Value for String
     */
    @JsonSetter("Prefix")
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * Getter for Suffix.
     * Name suffix
     * @return Returns the String
     */
    @JsonGetter("Suffix")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSuffix() {
        return suffix;
    }

    /**
     * Setter for Suffix.
     * Name suffix
     * @param suffix Value for String
     */
    @JsonSetter("Suffix")
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * Getter for Surname.
     * Surname
     * @return Returns the String
     */
    @JsonGetter("Surname")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSurname() {
        return surname;
    }

    /**
     * Setter for Surname.
     * Surname
     * @param surname Value for String
     */
    @JsonSetter("Surname")
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Converts this OutputNameDetail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OutputNameDetail [" + "forename=" + forename + ", middleNames=" + middleNames
                + ", prefix=" + prefix + ", suffix=" + suffix + ", surname=" + surname + "]";
    }

    /**
     * Builds a new {@link OutputNameDetail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OutputNameDetail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .forename(getForename())
                .middleNames(getMiddleNames())
                .prefix(getPrefix())
                .suffix(getSuffix())
                .surname(getSurname());
        return builder;
    }

    /**
     * Class to build instances of {@link OutputNameDetail}.
     */
    public static class Builder {
        private String forename;
        private String middleNames;
        private String prefix;
        private String suffix;
        private String surname;



        /**
         * Setter for forename.
         * @param  forename  String value for forename.
         * @return Builder
         */
        public Builder forename(String forename) {
            this.forename = forename;
            return this;
        }

        /**
         * Setter for middleNames.
         * @param  middleNames  String value for middleNames.
         * @return Builder
         */
        public Builder middleNames(String middleNames) {
            this.middleNames = middleNames;
            return this;
        }

        /**
         * Setter for prefix.
         * @param  prefix  String value for prefix.
         * @return Builder
         */
        public Builder prefix(String prefix) {
            this.prefix = prefix;
            return this;
        }

        /**
         * Setter for suffix.
         * @param  suffix  String value for suffix.
         * @return Builder
         */
        public Builder suffix(String suffix) {
            this.suffix = suffix;
            return this;
        }

        /**
         * Setter for surname.
         * @param  surname  String value for surname.
         * @return Builder
         */
        public Builder surname(String surname) {
            this.surname = surname;
            return this;
        }

        /**
         * Builds a new {@link OutputNameDetail} object using the set fields.
         * @return {@link OutputNameDetail}
         */
        public OutputNameDetail build() {
            return new OutputNameDetail(forename, middleNames, prefix, suffix, surname);
        }
    }
}
