/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;
import java.util.List;

/**
 * This is a model class for OwnCAISSummary type.
 */
public class OwnCAISSummary {
    private int sourceCode;
    private String ageSinceLastStatus8;
    private int summaryStatus0;
    private int summaryStatus1;
    private int summaryStatus2;
    private int summaryStatus3;
    private int summaryStatus4;
    private int summaryStatus5;
    private int summaryStatus6;
    private int summaryStatusU;
    private int summaryStatus8;
    private String summaryBalance;
    private String summaryBalanceIndicator;
    private int summaryActiveAccounts;
    private String summaryDefaultBalance;
    private String summaryDefaultBalanceIndicator;
    private int monthCount;
    private List<MonthlyData> monthlyData;

    /**
     * Default constructor.
     */
    public OwnCAISSummary() {
    }

    /**
     * Initialization constructor.
     * @param  sourceCode  int value for sourceCode.
     * @param  summaryStatus0  int value for summaryStatus0.
     * @param  summaryStatus1  int value for summaryStatus1.
     * @param  summaryStatus2  int value for summaryStatus2.
     * @param  summaryStatus3  int value for summaryStatus3.
     * @param  summaryStatus4  int value for summaryStatus4.
     * @param  summaryStatus5  int value for summaryStatus5.
     * @param  summaryStatus6  int value for summaryStatus6.
     * @param  summaryStatusU  int value for summaryStatusU.
     * @param  summaryStatus8  int value for summaryStatus8.
     * @param  summaryActiveAccounts  int value for summaryActiveAccounts.
     * @param  monthCount  int value for monthCount.
     * @param  ageSinceLastStatus8  String value for ageSinceLastStatus8.
     * @param  summaryBalance  String value for summaryBalance.
     * @param  summaryBalanceIndicator  String value for summaryBalanceIndicator.
     * @param  summaryDefaultBalance  String value for summaryDefaultBalance.
     * @param  summaryDefaultBalanceIndicator  String value for summaryDefaultBalanceIndicator.
     * @param  monthlyData  List of MonthlyData value for monthlyData.
     */
    public OwnCAISSummary(
            int sourceCode,
            int summaryStatus0,
            int summaryStatus1,
            int summaryStatus2,
            int summaryStatus3,
            int summaryStatus4,
            int summaryStatus5,
            int summaryStatus6,
            int summaryStatusU,
            int summaryStatus8,
            int summaryActiveAccounts,
            int monthCount,
            String ageSinceLastStatus8,
            String summaryBalance,
            String summaryBalanceIndicator,
            String summaryDefaultBalance,
            String summaryDefaultBalanceIndicator,
            List<MonthlyData> monthlyData) {
        this.sourceCode = sourceCode;
        this.ageSinceLastStatus8 = ageSinceLastStatus8;
        this.summaryStatus0 = summaryStatus0;
        this.summaryStatus1 = summaryStatus1;
        this.summaryStatus2 = summaryStatus2;
        this.summaryStatus3 = summaryStatus3;
        this.summaryStatus4 = summaryStatus4;
        this.summaryStatus5 = summaryStatus5;
        this.summaryStatus6 = summaryStatus6;
        this.summaryStatusU = summaryStatusU;
        this.summaryStatus8 = summaryStatus8;
        this.summaryBalance = summaryBalance;
        this.summaryBalanceIndicator = summaryBalanceIndicator;
        this.summaryActiveAccounts = summaryActiveAccounts;
        this.summaryDefaultBalance = summaryDefaultBalance;
        this.summaryDefaultBalanceIndicator = summaryDefaultBalanceIndicator;
        this.monthCount = monthCount;
        this.monthlyData = monthlyData;
    }

    /**
     * Getter for SourceCode.
     * The Source Code should be defined as numeric 4. Only returned for own CAIS accounts.
     * @return Returns the int
     */
    @JsonGetter("SourceCode")
    public int getSourceCode() {
        return sourceCode;
    }

    /**
     * Setter for SourceCode.
     * The Source Code should be defined as numeric 4. Only returned for own CAIS accounts.
     * @param sourceCode Value for int
     */
    @JsonSetter("SourceCode")
    public void setSourceCode(int sourceCode) {
        this.sourceCode = sourceCode;
    }

    /**
     * Getter for AgeSinceLastStatus8.
     * Time since last status 8 in months
     * @return Returns the String
     */
    @JsonGetter("AgeSinceLastStatus8")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAgeSinceLastStatus8() {
        return ageSinceLastStatus8;
    }

    /**
     * Setter for AgeSinceLastStatus8.
     * Time since last status 8 in months
     * @param ageSinceLastStatus8 Value for String
     */
    @JsonSetter("AgeSinceLastStatus8")
    public void setAgeSinceLastStatus8(String ageSinceLastStatus8) {
        this.ageSinceLastStatus8 = ageSinceLastStatus8;
    }

    /**
     * Getter for SummaryStatus0.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus0")
    public int getSummaryStatus0() {
        return summaryStatus0;
    }

    /**
     * Setter for SummaryStatus0.
     * @param summaryStatus0 Value for int
     */
    @JsonSetter("SummaryStatus0")
    public void setSummaryStatus0(int summaryStatus0) {
        this.summaryStatus0 = summaryStatus0;
    }

    /**
     * Getter for SummaryStatus1.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus1")
    public int getSummaryStatus1() {
        return summaryStatus1;
    }

    /**
     * Setter for SummaryStatus1.
     * @param summaryStatus1 Value for int
     */
    @JsonSetter("SummaryStatus1")
    public void setSummaryStatus1(int summaryStatus1) {
        this.summaryStatus1 = summaryStatus1;
    }

    /**
     * Getter for SummaryStatus2.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus2")
    public int getSummaryStatus2() {
        return summaryStatus2;
    }

    /**
     * Setter for SummaryStatus2.
     * @param summaryStatus2 Value for int
     */
    @JsonSetter("SummaryStatus2")
    public void setSummaryStatus2(int summaryStatus2) {
        this.summaryStatus2 = summaryStatus2;
    }

    /**
     * Getter for SummaryStatus3.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus3")
    public int getSummaryStatus3() {
        return summaryStatus3;
    }

    /**
     * Setter for SummaryStatus3.
     * @param summaryStatus3 Value for int
     */
    @JsonSetter("SummaryStatus3")
    public void setSummaryStatus3(int summaryStatus3) {
        this.summaryStatus3 = summaryStatus3;
    }

    /**
     * Getter for SummaryStatus4.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus4")
    public int getSummaryStatus4() {
        return summaryStatus4;
    }

    /**
     * Setter for SummaryStatus4.
     * @param summaryStatus4 Value for int
     */
    @JsonSetter("SummaryStatus4")
    public void setSummaryStatus4(int summaryStatus4) {
        this.summaryStatus4 = summaryStatus4;
    }

    /**
     * Getter for SummaryStatus5.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus5")
    public int getSummaryStatus5() {
        return summaryStatus5;
    }

    /**
     * Setter for SummaryStatus5.
     * @param summaryStatus5 Value for int
     */
    @JsonSetter("SummaryStatus5")
    public void setSummaryStatus5(int summaryStatus5) {
        this.summaryStatus5 = summaryStatus5;
    }

    /**
     * Getter for SummaryStatus6.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus6")
    public int getSummaryStatus6() {
        return summaryStatus6;
    }

    /**
     * Setter for SummaryStatus6.
     * @param summaryStatus6 Value for int
     */
    @JsonSetter("SummaryStatus6")
    public void setSummaryStatus6(int summaryStatus6) {
        this.summaryStatus6 = summaryStatus6;
    }

    /**
     * Getter for SummaryStatusU.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatusU")
    public int getSummaryStatusU() {
        return summaryStatusU;
    }

    /**
     * Setter for SummaryStatusU.
     * @param summaryStatusU Value for int
     */
    @JsonSetter("SummaryStatusU")
    public void setSummaryStatusU(int summaryStatusU) {
        this.summaryStatusU = summaryStatusU;
    }

    /**
     * Getter for SummaryStatus8.
     * @return Returns the int
     */
    @JsonGetter("SummaryStatus8")
    public int getSummaryStatus8() {
        return summaryStatus8;
    }

    /**
     * Setter for SummaryStatus8.
     * @param summaryStatus8 Value for int
     */
    @JsonSetter("SummaryStatus8")
    public void setSummaryStatus8(int summaryStatus8) {
        this.summaryStatus8 = summaryStatus8;
    }

    /**
     * Getter for SummaryBalance.
     * @return Returns the String
     */
    @JsonGetter("SummaryBalance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSummaryBalance() {
        return summaryBalance;
    }

    /**
     * Setter for SummaryBalance.
     * @param summaryBalance Value for String
     */
    @JsonSetter("SummaryBalance")
    public void setSummaryBalance(String summaryBalance) {
        this.summaryBalance = summaryBalance;
    }

    /**
     * Getter for SummaryBalanceIndicator.
     * @return Returns the String
     */
    @JsonGetter("SummaryBalanceIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSummaryBalanceIndicator() {
        return summaryBalanceIndicator;
    }

    /**
     * Setter for SummaryBalanceIndicator.
     * @param summaryBalanceIndicator Value for String
     */
    @JsonSetter("SummaryBalanceIndicator")
    public void setSummaryBalanceIndicator(String summaryBalanceIndicator) {
        this.summaryBalanceIndicator = summaryBalanceIndicator;
    }

    /**
     * Getter for SummaryActiveAccounts.
     * @return Returns the int
     */
    @JsonGetter("SummaryActiveAccounts")
    public int getSummaryActiveAccounts() {
        return summaryActiveAccounts;
    }

    /**
     * Setter for SummaryActiveAccounts.
     * @param summaryActiveAccounts Value for int
     */
    @JsonSetter("SummaryActiveAccounts")
    public void setSummaryActiveAccounts(int summaryActiveAccounts) {
        this.summaryActiveAccounts = summaryActiveAccounts;
    }

    /**
     * Getter for SummaryDefaultBalance.
     * @return Returns the String
     */
    @JsonGetter("SummaryDefaultBalance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSummaryDefaultBalance() {
        return summaryDefaultBalance;
    }

    /**
     * Setter for SummaryDefaultBalance.
     * @param summaryDefaultBalance Value for String
     */
    @JsonSetter("SummaryDefaultBalance")
    public void setSummaryDefaultBalance(String summaryDefaultBalance) {
        this.summaryDefaultBalance = summaryDefaultBalance;
    }

    /**
     * Getter for SummaryDefaultBalanceIndicator.
     * @return Returns the String
     */
    @JsonGetter("SummaryDefaultBalanceIndicator")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSummaryDefaultBalanceIndicator() {
        return summaryDefaultBalanceIndicator;
    }

    /**
     * Setter for SummaryDefaultBalanceIndicator.
     * @param summaryDefaultBalanceIndicator Value for String
     */
    @JsonSetter("SummaryDefaultBalanceIndicator")
    public void setSummaryDefaultBalanceIndicator(String summaryDefaultBalanceIndicator) {
        this.summaryDefaultBalanceIndicator = summaryDefaultBalanceIndicator;
    }

    /**
     * Getter for MonthCount.
     * @return Returns the int
     */
    @JsonGetter("MonthCount")
    public int getMonthCount() {
        return monthCount;
    }

    /**
     * Setter for MonthCount.
     * @param monthCount Value for int
     */
    @JsonSetter("MonthCount")
    public void setMonthCount(int monthCount) {
        this.monthCount = monthCount;
    }

    /**
     * Getter for MonthlyData.
     * @return Returns the List of MonthlyData
     */
    @JsonGetter("MonthlyData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<MonthlyData> getMonthlyData() {
        return monthlyData;
    }

    /**
     * Setter for MonthlyData.
     * @param monthlyData Value for List of MonthlyData
     */
    @JsonSetter("MonthlyData")
    public void setMonthlyData(List<MonthlyData> monthlyData) {
        this.monthlyData = monthlyData;
    }

    /**
     * Converts this OwnCAISSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OwnCAISSummary [" + "sourceCode=" + sourceCode + ", summaryStatus0="
                + summaryStatus0 + ", summaryStatus1=" + summaryStatus1 + ", summaryStatus2="
                + summaryStatus2 + ", summaryStatus3=" + summaryStatus3 + ", summaryStatus4="
                + summaryStatus4 + ", summaryStatus5=" + summaryStatus5 + ", summaryStatus6="
                + summaryStatus6 + ", summaryStatusU=" + summaryStatusU + ", summaryStatus8="
                + summaryStatus8 + ", summaryActiveAccounts=" + summaryActiveAccounts
                + ", monthCount=" + monthCount + ", ageSinceLastStatus8=" + ageSinceLastStatus8
                + ", summaryBalance=" + summaryBalance + ", summaryBalanceIndicator="
                + summaryBalanceIndicator + ", summaryDefaultBalance=" + summaryDefaultBalance
                + ", summaryDefaultBalanceIndicator=" + summaryDefaultBalanceIndicator
                + ", monthlyData=" + monthlyData + "]";
    }

    /**
     * Builds a new {@link OwnCAISSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OwnCAISSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(sourceCode, summaryStatus0, summaryStatus1, summaryStatus2,
                summaryStatus3, summaryStatus4, summaryStatus5, summaryStatus6, summaryStatusU,
                summaryStatus8, summaryActiveAccounts, monthCount)
                .ageSinceLastStatus8(getAgeSinceLastStatus8())
                .summaryBalance(getSummaryBalance())
                .summaryBalanceIndicator(getSummaryBalanceIndicator())
                .summaryDefaultBalance(getSummaryDefaultBalance())
                .summaryDefaultBalanceIndicator(getSummaryDefaultBalanceIndicator())
                .monthlyData(getMonthlyData());
        return builder;
    }

    /**
     * Class to build instances of {@link OwnCAISSummary}.
     */
    public static class Builder {
        private int sourceCode;
        private int summaryStatus0;
        private int summaryStatus1;
        private int summaryStatus2;
        private int summaryStatus3;
        private int summaryStatus4;
        private int summaryStatus5;
        private int summaryStatus6;
        private int summaryStatusU;
        private int summaryStatus8;
        private int summaryActiveAccounts;
        private int monthCount;
        private String ageSinceLastStatus8;
        private String summaryBalance;
        private String summaryBalanceIndicator;
        private String summaryDefaultBalance;
        private String summaryDefaultBalanceIndicator;
        private List<MonthlyData> monthlyData;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  sourceCode  int value for sourceCode.
         * @param  summaryStatus0  int value for summaryStatus0.
         * @param  summaryStatus1  int value for summaryStatus1.
         * @param  summaryStatus2  int value for summaryStatus2.
         * @param  summaryStatus3  int value for summaryStatus3.
         * @param  summaryStatus4  int value for summaryStatus4.
         * @param  summaryStatus5  int value for summaryStatus5.
         * @param  summaryStatus6  int value for summaryStatus6.
         * @param  summaryStatusU  int value for summaryStatusU.
         * @param  summaryStatus8  int value for summaryStatus8.
         * @param  summaryActiveAccounts  int value for summaryActiveAccounts.
         * @param  monthCount  int value for monthCount.
         */
        public Builder(int sourceCode, int summaryStatus0, int summaryStatus1, int summaryStatus2,
                int summaryStatus3, int summaryStatus4, int summaryStatus5, int summaryStatus6,
                int summaryStatusU, int summaryStatus8, int summaryActiveAccounts, int monthCount) {
            this.sourceCode = sourceCode;
            this.summaryStatus0 = summaryStatus0;
            this.summaryStatus1 = summaryStatus1;
            this.summaryStatus2 = summaryStatus2;
            this.summaryStatus3 = summaryStatus3;
            this.summaryStatus4 = summaryStatus4;
            this.summaryStatus5 = summaryStatus5;
            this.summaryStatus6 = summaryStatus6;
            this.summaryStatusU = summaryStatusU;
            this.summaryStatus8 = summaryStatus8;
            this.summaryActiveAccounts = summaryActiveAccounts;
            this.monthCount = monthCount;
        }

        /**
         * Setter for sourceCode.
         * @param  sourceCode  int value for sourceCode.
         * @return Builder
         */
        public Builder sourceCode(int sourceCode) {
            this.sourceCode = sourceCode;
            return this;
        }

        /**
         * Setter for summaryStatus0.
         * @param  summaryStatus0  int value for summaryStatus0.
         * @return Builder
         */
        public Builder summaryStatus0(int summaryStatus0) {
            this.summaryStatus0 = summaryStatus0;
            return this;
        }

        /**
         * Setter for summaryStatus1.
         * @param  summaryStatus1  int value for summaryStatus1.
         * @return Builder
         */
        public Builder summaryStatus1(int summaryStatus1) {
            this.summaryStatus1 = summaryStatus1;
            return this;
        }

        /**
         * Setter for summaryStatus2.
         * @param  summaryStatus2  int value for summaryStatus2.
         * @return Builder
         */
        public Builder summaryStatus2(int summaryStatus2) {
            this.summaryStatus2 = summaryStatus2;
            return this;
        }

        /**
         * Setter for summaryStatus3.
         * @param  summaryStatus3  int value for summaryStatus3.
         * @return Builder
         */
        public Builder summaryStatus3(int summaryStatus3) {
            this.summaryStatus3 = summaryStatus3;
            return this;
        }

        /**
         * Setter for summaryStatus4.
         * @param  summaryStatus4  int value for summaryStatus4.
         * @return Builder
         */
        public Builder summaryStatus4(int summaryStatus4) {
            this.summaryStatus4 = summaryStatus4;
            return this;
        }

        /**
         * Setter for summaryStatus5.
         * @param  summaryStatus5  int value for summaryStatus5.
         * @return Builder
         */
        public Builder summaryStatus5(int summaryStatus5) {
            this.summaryStatus5 = summaryStatus5;
            return this;
        }

        /**
         * Setter for summaryStatus6.
         * @param  summaryStatus6  int value for summaryStatus6.
         * @return Builder
         */
        public Builder summaryStatus6(int summaryStatus6) {
            this.summaryStatus6 = summaryStatus6;
            return this;
        }

        /**
         * Setter for summaryStatusU.
         * @param  summaryStatusU  int value for summaryStatusU.
         * @return Builder
         */
        public Builder summaryStatusU(int summaryStatusU) {
            this.summaryStatusU = summaryStatusU;
            return this;
        }

        /**
         * Setter for summaryStatus8.
         * @param  summaryStatus8  int value for summaryStatus8.
         * @return Builder
         */
        public Builder summaryStatus8(int summaryStatus8) {
            this.summaryStatus8 = summaryStatus8;
            return this;
        }

        /**
         * Setter for summaryActiveAccounts.
         * @param  summaryActiveAccounts  int value for summaryActiveAccounts.
         * @return Builder
         */
        public Builder summaryActiveAccounts(int summaryActiveAccounts) {
            this.summaryActiveAccounts = summaryActiveAccounts;
            return this;
        }

        /**
         * Setter for monthCount.
         * @param  monthCount  int value for monthCount.
         * @return Builder
         */
        public Builder monthCount(int monthCount) {
            this.monthCount = monthCount;
            return this;
        }

        /**
         * Setter for ageSinceLastStatus8.
         * @param  ageSinceLastStatus8  String value for ageSinceLastStatus8.
         * @return Builder
         */
        public Builder ageSinceLastStatus8(String ageSinceLastStatus8) {
            this.ageSinceLastStatus8 = ageSinceLastStatus8;
            return this;
        }

        /**
         * Setter for summaryBalance.
         * @param  summaryBalance  String value for summaryBalance.
         * @return Builder
         */
        public Builder summaryBalance(String summaryBalance) {
            this.summaryBalance = summaryBalance;
            return this;
        }

        /**
         * Setter for summaryBalanceIndicator.
         * @param  summaryBalanceIndicator  String value for summaryBalanceIndicator.
         * @return Builder
         */
        public Builder summaryBalanceIndicator(String summaryBalanceIndicator) {
            this.summaryBalanceIndicator = summaryBalanceIndicator;
            return this;
        }

        /**
         * Setter for summaryDefaultBalance.
         * @param  summaryDefaultBalance  String value for summaryDefaultBalance.
         * @return Builder
         */
        public Builder summaryDefaultBalance(String summaryDefaultBalance) {
            this.summaryDefaultBalance = summaryDefaultBalance;
            return this;
        }

        /**
         * Setter for summaryDefaultBalanceIndicator.
         * @param  summaryDefaultBalanceIndicator  String value for summaryDefaultBalanceIndicator.
         * @return Builder
         */
        public Builder summaryDefaultBalanceIndicator(String summaryDefaultBalanceIndicator) {
            this.summaryDefaultBalanceIndicator = summaryDefaultBalanceIndicator;
            return this;
        }

        /**
         * Setter for monthlyData.
         * @param  monthlyData  List of MonthlyData value for monthlyData.
         * @return Builder
         */
        public Builder monthlyData(List<MonthlyData> monthlyData) {
            this.monthlyData = monthlyData;
            return this;
        }

        /**
         * Builds a new {@link OwnCAISSummary} object using the set fields.
         * @return {@link OwnCAISSummary}
         */
        public OwnCAISSummary build() {
            return new OwnCAISSummary(sourceCode, summaryStatus0, summaryStatus1, summaryStatus2,
                    summaryStatus3, summaryStatus4, summaryStatus5, summaryStatus6, summaryStatusU,
                    summaryStatus8, summaryActiveAccounts, monthCount, ageSinceLastStatus8,
                    summaryBalance, summaryBalanceIndicator, summaryDefaultBalance,
                    summaryDefaultBalanceIndicator, monthlyData);
        }
    }
}
