/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for PaymentSummary type.
 */
public class PaymentSummary {
    private String anocFlag;
    private String associatedDataOutsideOwnership;
    private String dateOwnershipCommencedMm;
    private String dateOwnershipCommencedYyyy;
    private String dateOwnershipTerminatedYyyy;
    private String dateownershipTerminatedMm;
    private String mainDataOutsideOwnership;
    private String mnocFlag;
    private int numMonthsPaymentPreformance;
    private int numOccuranceCommon;

    /**
     * Default constructor.
     */
    public PaymentSummary() {
    }

    /**
     * Initialization constructor.
     * @param  numMonthsPaymentPreformance  int value for numMonthsPaymentPreformance.
     * @param  numOccuranceCommon  int value for numOccuranceCommon.
     * @param  anocFlag  String value for anocFlag.
     * @param  associatedDataOutsideOwnership  String value for associatedDataOutsideOwnership.
     * @param  dateOwnershipCommencedMm  String value for dateOwnershipCommencedMm.
     * @param  dateOwnershipCommencedYyyy  String value for dateOwnershipCommencedYyyy.
     * @param  dateOwnershipTerminatedYyyy  String value for dateOwnershipTerminatedYyyy.
     * @param  dateownershipTerminatedMm  String value for dateownershipTerminatedMm.
     * @param  mainDataOutsideOwnership  String value for mainDataOutsideOwnership.
     * @param  mnocFlag  String value for mnocFlag.
     */
    public PaymentSummary(
            int numMonthsPaymentPreformance,
            int numOccuranceCommon,
            String anocFlag,
            String associatedDataOutsideOwnership,
            String dateOwnershipCommencedMm,
            String dateOwnershipCommencedYyyy,
            String dateOwnershipTerminatedYyyy,
            String dateownershipTerminatedMm,
            String mainDataOutsideOwnership,
            String mnocFlag) {
        this.anocFlag = anocFlag;
        this.associatedDataOutsideOwnership = associatedDataOutsideOwnership;
        this.dateOwnershipCommencedMm = dateOwnershipCommencedMm;
        this.dateOwnershipCommencedYyyy = dateOwnershipCommencedYyyy;
        this.dateOwnershipTerminatedYyyy = dateOwnershipTerminatedYyyy;
        this.dateownershipTerminatedMm = dateownershipTerminatedMm;
        this.mainDataOutsideOwnership = mainDataOutsideOwnership;
        this.mnocFlag = mnocFlag;
        this.numMonthsPaymentPreformance = numMonthsPaymentPreformance;
        this.numOccuranceCommon = numOccuranceCommon;
    }

    /**
     * Getter for AnocFlag.
     * @return Returns the String
     */
    @JsonGetter("AnocFlag")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAnocFlag() {
        return anocFlag;
    }

    /**
     * Setter for AnocFlag.
     * @param anocFlag Value for String
     */
    @JsonSetter("AnocFlag")
    public void setAnocFlag(String anocFlag) {
        this.anocFlag = anocFlag;
    }

    /**
     * Getter for AssociatedDataOutsideOwnership.
     * @return Returns the String
     */
    @JsonGetter("AssociatedDataOutsideOwnership")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAssociatedDataOutsideOwnership() {
        return associatedDataOutsideOwnership;
    }

    /**
     * Setter for AssociatedDataOutsideOwnership.
     * @param associatedDataOutsideOwnership Value for String
     */
    @JsonSetter("AssociatedDataOutsideOwnership")
    public void setAssociatedDataOutsideOwnership(String associatedDataOutsideOwnership) {
        this.associatedDataOutsideOwnership = associatedDataOutsideOwnership;
    }

    /**
     * Getter for DateOwnershipCommencedMm.
     * @return Returns the String
     */
    @JsonGetter("DateOwnershipCommenced-Mm")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDateOwnershipCommencedMm() {
        return dateOwnershipCommencedMm;
    }

    /**
     * Setter for DateOwnershipCommencedMm.
     * @param dateOwnershipCommencedMm Value for String
     */
    @JsonSetter("DateOwnershipCommenced-Mm")
    public void setDateOwnershipCommencedMm(String dateOwnershipCommencedMm) {
        this.dateOwnershipCommencedMm = dateOwnershipCommencedMm;
    }

    /**
     * Getter for DateOwnershipCommencedYyyy.
     * @return Returns the String
     */
    @JsonGetter("DateOwnershipCommenced-Yyyy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDateOwnershipCommencedYyyy() {
        return dateOwnershipCommencedYyyy;
    }

    /**
     * Setter for DateOwnershipCommencedYyyy.
     * @param dateOwnershipCommencedYyyy Value for String
     */
    @JsonSetter("DateOwnershipCommenced-Yyyy")
    public void setDateOwnershipCommencedYyyy(String dateOwnershipCommencedYyyy) {
        this.dateOwnershipCommencedYyyy = dateOwnershipCommencedYyyy;
    }

    /**
     * Getter for DateOwnershipTerminatedYyyy.
     * @return Returns the String
     */
    @JsonGetter("DateOwnershipTerminated-Yyyy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDateOwnershipTerminatedYyyy() {
        return dateOwnershipTerminatedYyyy;
    }

    /**
     * Setter for DateOwnershipTerminatedYyyy.
     * @param dateOwnershipTerminatedYyyy Value for String
     */
    @JsonSetter("DateOwnershipTerminated-Yyyy")
    public void setDateOwnershipTerminatedYyyy(String dateOwnershipTerminatedYyyy) {
        this.dateOwnershipTerminatedYyyy = dateOwnershipTerminatedYyyy;
    }

    /**
     * Getter for DateownershipTerminatedMm.
     * @return Returns the String
     */
    @JsonGetter("DateownershipTerminated-Mm")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDateownershipTerminatedMm() {
        return dateownershipTerminatedMm;
    }

    /**
     * Setter for DateownershipTerminatedMm.
     * @param dateownershipTerminatedMm Value for String
     */
    @JsonSetter("DateownershipTerminated-Mm")
    public void setDateownershipTerminatedMm(String dateownershipTerminatedMm) {
        this.dateownershipTerminatedMm = dateownershipTerminatedMm;
    }

    /**
     * Getter for MainDataOutsideOwnership.
     * @return Returns the String
     */
    @JsonGetter("MainDataOutsideOwnership")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMainDataOutsideOwnership() {
        return mainDataOutsideOwnership;
    }

    /**
     * Setter for MainDataOutsideOwnership.
     * @param mainDataOutsideOwnership Value for String
     */
    @JsonSetter("MainDataOutsideOwnership")
    public void setMainDataOutsideOwnership(String mainDataOutsideOwnership) {
        this.mainDataOutsideOwnership = mainDataOutsideOwnership;
    }

    /**
     * Getter for MnocFlag.
     * @return Returns the String
     */
    @JsonGetter("MnocFlag")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMnocFlag() {
        return mnocFlag;
    }

    /**
     * Setter for MnocFlag.
     * @param mnocFlag Value for String
     */
    @JsonSetter("MnocFlag")
    public void setMnocFlag(String mnocFlag) {
        this.mnocFlag = mnocFlag;
    }

    /**
     * Getter for NumMonthsPaymentPreformance.
     * @return Returns the int
     */
    @JsonGetter("NumMonthsPaymentPreformance")
    public int getNumMonthsPaymentPreformance() {
        return numMonthsPaymentPreformance;
    }

    /**
     * Setter for NumMonthsPaymentPreformance.
     * @param numMonthsPaymentPreformance Value for int
     */
    @JsonSetter("NumMonthsPaymentPreformance")
    public void setNumMonthsPaymentPreformance(int numMonthsPaymentPreformance) {
        this.numMonthsPaymentPreformance = numMonthsPaymentPreformance;
    }

    /**
     * Getter for NumOccuranceCommon.
     * @return Returns the int
     */
    @JsonGetter("NumOccuranceCommon")
    public int getNumOccuranceCommon() {
        return numOccuranceCommon;
    }

    /**
     * Setter for NumOccuranceCommon.
     * @param numOccuranceCommon Value for int
     */
    @JsonSetter("NumOccuranceCommon")
    public void setNumOccuranceCommon(int numOccuranceCommon) {
        this.numOccuranceCommon = numOccuranceCommon;
    }

    /**
     * Converts this PaymentSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentSummary [" + "numMonthsPaymentPreformance=" + numMonthsPaymentPreformance
                + ", numOccuranceCommon=" + numOccuranceCommon + ", anocFlag=" + anocFlag
                + ", associatedDataOutsideOwnership=" + associatedDataOutsideOwnership
                + ", dateOwnershipCommencedMm=" + dateOwnershipCommencedMm
                + ", dateOwnershipCommencedYyyy=" + dateOwnershipCommencedYyyy
                + ", dateOwnershipTerminatedYyyy=" + dateOwnershipTerminatedYyyy
                + ", dateownershipTerminatedMm=" + dateownershipTerminatedMm
                + ", mainDataOutsideOwnership=" + mainDataOutsideOwnership + ", mnocFlag="
                + mnocFlag + "]";
    }

    /**
     * Builds a new {@link PaymentSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaymentSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(numMonthsPaymentPreformance, numOccuranceCommon)
                .anocFlag(getAnocFlag())
                .associatedDataOutsideOwnership(getAssociatedDataOutsideOwnership())
                .dateOwnershipCommencedMm(getDateOwnershipCommencedMm())
                .dateOwnershipCommencedYyyy(getDateOwnershipCommencedYyyy())
                .dateOwnershipTerminatedYyyy(getDateOwnershipTerminatedYyyy())
                .dateownershipTerminatedMm(getDateownershipTerminatedMm())
                .mainDataOutsideOwnership(getMainDataOutsideOwnership())
                .mnocFlag(getMnocFlag());
        return builder;
    }

    /**
     * Class to build instances of {@link PaymentSummary}.
     */
    public static class Builder {
        private int numMonthsPaymentPreformance;
        private int numOccuranceCommon;
        private String anocFlag;
        private String associatedDataOutsideOwnership;
        private String dateOwnershipCommencedMm;
        private String dateOwnershipCommencedYyyy;
        private String dateOwnershipTerminatedYyyy;
        private String dateownershipTerminatedMm;
        private String mainDataOutsideOwnership;
        private String mnocFlag;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  numMonthsPaymentPreformance  int value for numMonthsPaymentPreformance.
         * @param  numOccuranceCommon  int value for numOccuranceCommon.
         */
        public Builder(int numMonthsPaymentPreformance, int numOccuranceCommon) {
            this.numMonthsPaymentPreformance = numMonthsPaymentPreformance;
            this.numOccuranceCommon = numOccuranceCommon;
        }

        /**
         * Setter for numMonthsPaymentPreformance.
         * @param  numMonthsPaymentPreformance  int value for numMonthsPaymentPreformance.
         * @return Builder
         */
        public Builder numMonthsPaymentPreformance(int numMonthsPaymentPreformance) {
            this.numMonthsPaymentPreformance = numMonthsPaymentPreformance;
            return this;
        }

        /**
         * Setter for numOccuranceCommon.
         * @param  numOccuranceCommon  int value for numOccuranceCommon.
         * @return Builder
         */
        public Builder numOccuranceCommon(int numOccuranceCommon) {
            this.numOccuranceCommon = numOccuranceCommon;
            return this;
        }

        /**
         * Setter for anocFlag.
         * @param  anocFlag  String value for anocFlag.
         * @return Builder
         */
        public Builder anocFlag(String anocFlag) {
            this.anocFlag = anocFlag;
            return this;
        }

        /**
         * Setter for associatedDataOutsideOwnership.
         * @param  associatedDataOutsideOwnership  String value for associatedDataOutsideOwnership.
         * @return Builder
         */
        public Builder associatedDataOutsideOwnership(String associatedDataOutsideOwnership) {
            this.associatedDataOutsideOwnership = associatedDataOutsideOwnership;
            return this;
        }

        /**
         * Setter for dateOwnershipCommencedMm.
         * @param  dateOwnershipCommencedMm  String value for dateOwnershipCommencedMm.
         * @return Builder
         */
        public Builder dateOwnershipCommencedMm(String dateOwnershipCommencedMm) {
            this.dateOwnershipCommencedMm = dateOwnershipCommencedMm;
            return this;
        }

        /**
         * Setter for dateOwnershipCommencedYyyy.
         * @param  dateOwnershipCommencedYyyy  String value for dateOwnershipCommencedYyyy.
         * @return Builder
         */
        public Builder dateOwnershipCommencedYyyy(String dateOwnershipCommencedYyyy) {
            this.dateOwnershipCommencedYyyy = dateOwnershipCommencedYyyy;
            return this;
        }

        /**
         * Setter for dateOwnershipTerminatedYyyy.
         * @param  dateOwnershipTerminatedYyyy  String value for dateOwnershipTerminatedYyyy.
         * @return Builder
         */
        public Builder dateOwnershipTerminatedYyyy(String dateOwnershipTerminatedYyyy) {
            this.dateOwnershipTerminatedYyyy = dateOwnershipTerminatedYyyy;
            return this;
        }

        /**
         * Setter for dateownershipTerminatedMm.
         * @param  dateownershipTerminatedMm  String value for dateownershipTerminatedMm.
         * @return Builder
         */
        public Builder dateownershipTerminatedMm(String dateownershipTerminatedMm) {
            this.dateownershipTerminatedMm = dateownershipTerminatedMm;
            return this;
        }

        /**
         * Setter for mainDataOutsideOwnership.
         * @param  mainDataOutsideOwnership  String value for mainDataOutsideOwnership.
         * @return Builder
         */
        public Builder mainDataOutsideOwnership(String mainDataOutsideOwnership) {
            this.mainDataOutsideOwnership = mainDataOutsideOwnership;
            return this;
        }

        /**
         * Setter for mnocFlag.
         * @param  mnocFlag  String value for mnocFlag.
         * @return Builder
         */
        public Builder mnocFlag(String mnocFlag) {
            this.mnocFlag = mnocFlag;
            return this;
        }

        /**
         * Builds a new {@link PaymentSummary} object using the set fields.
         * @return {@link PaymentSummary}
         */
        public PaymentSummary build() {
            return new PaymentSummary(numMonthsPaymentPreformance, numOccuranceCommon, anocFlag,
                    associatedDataOutsideOwnership, dateOwnershipCommencedMm,
                    dateOwnershipCommencedYyyy, dateOwnershipTerminatedYyyy,
                    dateownershipTerminatedMm, mainDataOutsideOwnership, mnocFlag);
        }
    }
}
