/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for PreviousSearchDetail type.
 */
public class PreviousSearchDetail {
    private String searchDate;
    private String enquiryType;
    private String ownEnquiryFlag;
    private PrevSearchSICInfo sICInformation;

    /**
     * Default constructor.
     */
    public PreviousSearchDetail() {
    }

    /**
     * Initialization constructor.
     * @param  searchDate  String value for searchDate.
     * @param  enquiryType  String value for enquiryType.
     * @param  ownEnquiryFlag  String value for ownEnquiryFlag.
     * @param  sICInformation  PrevSearchSICInfo value for sICInformation.
     */
    public PreviousSearchDetail(
            String searchDate,
            String enquiryType,
            String ownEnquiryFlag,
            PrevSearchSICInfo sICInformation) {
        this.searchDate = searchDate;
        this.enquiryType = enquiryType;
        this.ownEnquiryFlag = ownEnquiryFlag;
        this.sICInformation = sICInformation;
    }

    /**
     * Getter for SearchDate.
     * Previous search date (yyyy-mm-dd)
     * @return Returns the String
     */
    @JsonGetter("SearchDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSearchDate() {
        return searchDate;
    }

    /**
     * Setter for SearchDate.
     * Previous search date (yyyy-mm-dd)
     * @param searchDate Value for String
     */
    @JsonSetter("SearchDate")
    public void setSearchDate(String searchDate) {
        this.searchDate = searchDate;
    }

    /**
     * Getter for EnquiryType.
     * Indicator showing search enquiry type against the limited company. A = Registered Office /
     * Company Profile; B = Director Information; C = CPU Link Enquiry; D = e-series business Gold
     * Report; E = e-series business Silver Report; F = e-series business Bronze Report; G =
     * e-series business Basic Report; H = e-series business Document Image; I = e-series business
     * Corporate Tree Report; J = e-series business Enhanced Corporate Tree Report; L = BIGNet
     * Report; M = Report Builder; N = Commercial Autoscore Application; O = Commercial Autoscore
     * Reprocess Decision; P = e-series business Mortgages & Charges Report; X = XML Bespoke
     * Delivery; 1 = Registered Office / Company Profile ;2 = Registered Office / Company Profile; 3
     * = Profile and Credit; 4 = Profile and Credit; 5 = Microfiche / Document Copy Request; 6 =
     * Written Report; 7 = On-line Report (Legacy); 8 = On-line Report (Legacy); 9 = Financial
     * Analysis; Other = Non-Specific Report
     * @return Returns the String
     */
    @JsonGetter("EnquiryType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEnquiryType() {
        return enquiryType;
    }

    /**
     * Setter for EnquiryType.
     * Indicator showing search enquiry type against the limited company. A = Registered Office /
     * Company Profile; B = Director Information; C = CPU Link Enquiry; D = e-series business Gold
     * Report; E = e-series business Silver Report; F = e-series business Bronze Report; G =
     * e-series business Basic Report; H = e-series business Document Image; I = e-series business
     * Corporate Tree Report; J = e-series business Enhanced Corporate Tree Report; L = BIGNet
     * Report; M = Report Builder; N = Commercial Autoscore Application; O = Commercial Autoscore
     * Reprocess Decision; P = e-series business Mortgages & Charges Report; X = XML Bespoke
     * Delivery; 1 = Registered Office / Company Profile ;2 = Registered Office / Company Profile; 3
     * = Profile and Credit; 4 = Profile and Credit; 5 = Microfiche / Document Copy Request; 6 =
     * Written Report; 7 = On-line Report (Legacy); 8 = On-line Report (Legacy); 9 = Financial
     * Analysis; Other = Non-Specific Report
     * @param enquiryType Value for String
     */
    @JsonSetter("EnquiryType")
    public void setEnquiryType(String enquiryType) {
        this.enquiryType = enquiryType;
    }

    /**
     * Getter for OwnEnquiryFlag.
     * Indicator showing whether the enquiry was raised by the limited company - Y = Own enquiry; N
     * = Not own enquiry
     * @return Returns the String
     */
    @JsonGetter("OwnEnquiryFlag")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getOwnEnquiryFlag() {
        return ownEnquiryFlag;
    }

    /**
     * Setter for OwnEnquiryFlag.
     * Indicator showing whether the enquiry was raised by the limited company - Y = Own enquiry; N
     * = Not own enquiry
     * @param ownEnquiryFlag Value for String
     */
    @JsonSetter("OwnEnquiryFlag")
    public void setOwnEnquiryFlag(String ownEnquiryFlag) {
        this.ownEnquiryFlag = ownEnquiryFlag;
    }

    /**
     * Getter for SICInformation.
     * @return Returns the PrevSearchSICInfo
     */
    @JsonGetter("SICInformation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PrevSearchSICInfo getSICInformation() {
        return sICInformation;
    }

    /**
     * Setter for SICInformation.
     * @param sICInformation Value for PrevSearchSICInfo
     */
    @JsonSetter("SICInformation")
    public void setSICInformation(PrevSearchSICInfo sICInformation) {
        this.sICInformation = sICInformation;
    }

    /**
     * Converts this PreviousSearchDetail into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PreviousSearchDetail [" + "searchDate=" + searchDate + ", enquiryType="
                + enquiryType + ", ownEnquiryFlag=" + ownEnquiryFlag + ", sICInformation="
                + sICInformation + "]";
    }

    /**
     * Builds a new {@link PreviousSearchDetail.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PreviousSearchDetail.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .searchDate(getSearchDate())
                .enquiryType(getEnquiryType())
                .ownEnquiryFlag(getOwnEnquiryFlag())
                .sICInformation(getSICInformation());
        return builder;
    }

    /**
     * Class to build instances of {@link PreviousSearchDetail}.
     */
    public static class Builder {
        private String searchDate;
        private String enquiryType;
        private String ownEnquiryFlag;
        private PrevSearchSICInfo sICInformation;



        /**
         * Setter for searchDate.
         * @param  searchDate  String value for searchDate.
         * @return Builder
         */
        public Builder searchDate(String searchDate) {
            this.searchDate = searchDate;
            return this;
        }

        /**
         * Setter for enquiryType.
         * @param  enquiryType  String value for enquiryType.
         * @return Builder
         */
        public Builder enquiryType(String enquiryType) {
            this.enquiryType = enquiryType;
            return this;
        }

        /**
         * Setter for ownEnquiryFlag.
         * @param  ownEnquiryFlag  String value for ownEnquiryFlag.
         * @return Builder
         */
        public Builder ownEnquiryFlag(String ownEnquiryFlag) {
            this.ownEnquiryFlag = ownEnquiryFlag;
            return this;
        }

        /**
         * Setter for sICInformation.
         * @param  sICInformation  PrevSearchSICInfo value for sICInformation.
         * @return Builder
         */
        public Builder sICInformation(PrevSearchSICInfo sICInformation) {
            this.sICInformation = sICInformation;
            return this;
        }

        /**
         * Builds a new {@link PreviousSearchDetail} object using the set fields.
         * @return {@link PreviousSearchDetail}
         */
        public PreviousSearchDetail build() {
            return new PreviousSearchDetail(searchDate, enquiryType, ownEnquiryFlag,
                    sICInformation);
        }
    }
}
