/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for TimeInEmployment type.
 */
public class TimeInEmployment {
    private String months;
    private String years;

    /**
     * Default constructor.
     */
    public TimeInEmployment() {
    }

    /**
     * Initialization constructor.
     * @param  months  String value for months.
     * @param  years  String value for years.
     */
    public TimeInEmployment(
            String months,
            String years) {
        this.months = months;
        this.years = years;
    }

    /**
     * Getter for Months.
     * @return Returns the String
     */
    @JsonGetter("Months")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMonths() {
        return months;
    }

    /**
     * Setter for Months.
     * @param months Value for String
     */
    @JsonSetter("Months")
    public void setMonths(String months) {
        this.months = months;
    }

    /**
     * Getter for Years.
     * @return Returns the String
     */
    @JsonGetter("Years")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getYears() {
        return years;
    }

    /**
     * Setter for Years.
     * @param years Value for String
     */
    @JsonSetter("Years")
    public void setYears(String years) {
        this.years = years;
    }

    /**
     * Converts this TimeInEmployment into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TimeInEmployment [" + "months=" + months + ", years=" + years + "]";
    }

    /**
     * Builds a new {@link TimeInEmployment.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TimeInEmployment.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .months(getMonths())
                .years(getYears());
        return builder;
    }

    /**
     * Class to build instances of {@link TimeInEmployment}.
     */
    public static class Builder {
        private String months;
        private String years;



        /**
         * Setter for months.
         * @param  months  String value for months.
         * @return Builder
         */
        public Builder months(String months) {
            this.months = months;
            return this;
        }

        /**
         * Setter for years.
         * @param  years  String value for years.
         * @return Builder
         */
        public Builder years(String years) {
            this.years = years;
            return this;
        }

        /**
         * Builds a new {@link TimeInEmployment} object using the set fields.
         * @return {@link TimeInEmployment}
         */
        public TimeInEmployment build() {
            return new TimeInEmployment(months, years);
        }
    }
}
