/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for TradeNames type.
 */
public class TradeNames {
    private String tradingName;

    /**
     * Default constructor.
     */
    public TradeNames() {
    }

    /**
     * Initialization constructor.
     * @param  tradingName  String value for tradingName.
     */
    public TradeNames(
            String tradingName) {
        this.tradingName = tradingName;
    }

    /**
     * Getter for TradingName.
     * Licensee Trading Name
     * @return Returns the String
     */
    @JsonGetter("TradingName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTradingName() {
        return tradingName;
    }

    /**
     * Setter for TradingName.
     * Licensee Trading Name
     * @param tradingName Value for String
     */
    @JsonSetter("TradingName")
    public void setTradingName(String tradingName) {
        this.tradingName = tradingName;
    }

    /**
     * Converts this TradeNames into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TradeNames [" + "tradingName=" + tradingName + "]";
    }

    /**
     * Builds a new {@link TradeNames.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TradeNames.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .tradingName(getTradingName());
        return builder;
    }

    /**
     * Class to build instances of {@link TradeNames}.
     */
    public static class Builder {
        private String tradingName;



        /**
         * Setter for tradingName.
         * @param  tradingName  String value for tradingName.
         * @return Builder
         */
        public Builder tradingName(String tradingName) {
            this.tradingName = tradingName;
            return this;
        }

        /**
         * Builds a new {@link TradeNames} object using the set fields.
         * @return {@link TradeNames}
         */
        public TradeNames build() {
            return new TradeNames(tradingName);
        }
    }
}
