/*
 * CommercialCreditAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.experian.sandboxusapi.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.BaseModel;

/**
 * This is a model class for UnpaidAccountsDetails type.
 */
public class UnpaidAccountsDetails {
    private Integer unpaidAccounts;

    /**
     * Default constructor.
     */
    public UnpaidAccountsDetails() {
    }

    /**
     * Initialization constructor.
     * @param  unpaidAccounts  Integer value for unpaidAccounts.
     */
    public UnpaidAccountsDetails(
            Integer unpaidAccounts) {
        this.unpaidAccounts = unpaidAccounts;
    }

    /**
     * Getter for UnpaidAccounts.
     * Number of outstanding unpaid accounts by month for the limited company
     * @return Returns the Integer
     */
    @JsonGetter("UnpaidAccounts")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnpaidAccounts() {
        return unpaidAccounts;
    }

    /**
     * Setter for UnpaidAccounts.
     * Number of outstanding unpaid accounts by month for the limited company
     * @param unpaidAccounts Value for Integer
     */
    @JsonSetter("UnpaidAccounts")
    public void setUnpaidAccounts(Integer unpaidAccounts) {
        this.unpaidAccounts = unpaidAccounts;
    }

    /**
     * Converts this UnpaidAccountsDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UnpaidAccountsDetails [" + "unpaidAccounts=" + unpaidAccounts + "]";
    }

    /**
     * Builds a new {@link UnpaidAccountsDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UnpaidAccountsDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .unpaidAccounts(getUnpaidAccounts());
        return builder;
    }

    /**
     * Class to build instances of {@link UnpaidAccountsDetails}.
     */
    public static class Builder {
        private Integer unpaidAccounts;



        /**
         * Setter for unpaidAccounts.
         * @param  unpaidAccounts  Integer value for unpaidAccounts.
         * @return Builder
         */
        public Builder unpaidAccounts(Integer unpaidAccounts) {
            this.unpaidAccounts = unpaidAccounts;
            return this;
        }

        /**
         * Builds a new {@link UnpaidAccountsDetails} object using the set fields.
         * @return {@link UnpaidAccountsDetails}
         */
        public UnpaidAccountsDetails build() {
            return new UnpaidAccountsDetails(unpaidAccounts);
        }
    }
}
